#!/usr/bin/env node
// Bake the PIXEL RESOLVE placeholders: src/art_thumbs.js, one tiny inline
// thumbnail per dialog painting (assets/art/*.webp cut to the dialog box's
// 11:14 — the scene pieces; the opening slides and the safety backdrop are
// other shapes and are skipped).
//
// modal_shell.js opens an uncached painting on its solid TONE and resolves
// it through ever finer mosaics cut from the thumbnail while the painting
// loads, then fades the painting in. Both are inline, so they cost no
// request: that is the whole point of them.
//
//   node tools/art_thumbs.js      # rewrite src/art_thumbs.js
//
// tools/gen_story_art.js runs this after it writes a piece; run it by hand
// after editing assets/art/ any other way (scene_art.test.js fails on a
// painting with no thumbnail).

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const ART = path.join(ROOT, 'assets', 'art');
const OUT = path.join(ROOT, 'src', 'art_thumbs.js');
// 22×28 is the box's own 11:14 at two thumbnail pixels per unit: each
// mosaic tile lands 16px on screen — chunky enough to read as a resolve, fine
// enough to show where the subject is.
const THUMB_W = 22, THUMB_H = 28;

const py = `
import sys, glob, os, io, base64, json
from PIL import Image
out = {}
for f in sorted(glob.glob(os.path.join(sys.argv[1], '*.webp'))):
    im = Image.open(f).convert('RGB')
    if abs(im.width / im.height - 352 / 448) > 0.01:
        continue
    t = im.resize((${THUMB_W}, ${THUMB_H}), Image.BOX)
    b = io.BytesIO()
    t.save(b, 'WEBP', quality=70, method=6)
    # The TONE is the painting's average over its DETAIL zone (the top 42%,
    # where the subject is) — the quiet zone is dark by rule and would pull
    # every tone to the same brown.
    top = im.crop((0, 0, im.width, round(im.height * 0.42))).resize((1, 1), Image.BOX).getpixel((0, 0))
    out[os.path.splitext(os.path.basename(f))[0]] = {
        't': 'data:image/webp;base64,' + base64.b64encode(b.getvalue()).decode(),
        'c': '#%02x%02x%02x' % top,
    }
print(json.dumps(out))
`;
const thumbs = JSON.parse(execFileSync('python3', ['-c', py, ART]).toString());
const thumbBody = Object.entries(thumbs).map(([k, v]) => `  ${k}: '${v.t}',`).join('\n');
const toneBody = Object.entries(thumbs).map(([k, v]) => `  ${k}: '${v.c}',`).join('\n');
fs.writeFileSync(OUT,
  '// GENERATED by tools/art_thumbs.js — do not edit by hand.\n' +
  '// PIXEL RESOLVE placeholders for the dialog paintings (modal_shell.js):\n' +
  `// one ${THUMB_W}×${THUMB_H} inline WebP per assets/art scene piece, and the\n` +
  '// solid TONE each one resolves out of (its detail zone\'s average).\n' +
  `const ART_THUMBS = {\n${thumbBody}\n};\n` +
  `const ART_TONES = {\n${toneBody}\n};\n`);
console.log(`${path.relative(ROOT, OUT)}: ${Object.keys(thumbs).length} thumbnails, ` +
  `${Math.round(fs.statSync(OUT).size / 1024)} KB`);
