#!/usr/bin/env node
// Bake the PIXEL RESOLVE placeholders: src/art_thumbs.js, one tiny inline
// thumbnail per dialog painting (assets/art/*.webp cut to the dialog box's
// 11:14 — the scene pieces; the opening slides and the safety backdrop are
// other shapes and are skipped).
//
// modal_shell.js opens an uncached painting on its solid TONE and resolves
// it through ever finer mosaics cut from the thumbnail while the painting
// loads, then fades the painting in. Both are inline, so they cost no
// request: that is the whole point of them.
//
//   node tools/art_thumbs.js      # rewrite src/art_thumbs.js
//
// tools/gen_story_art.js runs this after it writes a piece; run it by hand
// after editing assets/art/ any other way (scene_art.test.js fails on a
// painting with no thumbnail).

const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');

const ROOT = path.join(__dirname, '..');
const ART = path.join(ROOT, 'assets', 'art');
const OUT = path.join(ROOT, 'src', 'art_thumbs.js');
// 22×28 is the box's own 11:14 at two thumbnail pixels per unit: each
// mosaic tile lands 16px on screen — chunky enough to read as a resolve, fine
// enough to show where the subject is.
const THUMB_W = 22, THUMB_H = 28;
// The PIXEL RESOLVE steps, coarse to fine (widths; heights keep 11:14), the
// last the thumbnail itself. Baked HERE, not cut at runtime: cutting them in
// the browser meant four canvas.toDataURL calls when a dialog opened — a GPU
// readback each, ~200 ms of main thread in the perf loop (render-loop audit,
// 2026-09-27). Written out as ART_CUT_WIDTHS so the shell steps through
// exactly the cuts that exist.
const CUT_WIDTHS = [3, 6, 11, THUMB_W];

const py = `
import sys, glob, os, io, base64, json
from PIL import Image
out = {}
for f in sorted(glob.glob(os.path.join(sys.argv[1], '*.webp'))):
    im = Image.open(f).convert('RGB')
    if abs(im.width / im.height - 352 / 448) > 0.01:
        continue
    t = im.resize((${THUMB_W}, ${THUMB_H}), Image.BOX)
    b = io.BytesIO()
    t.save(b, 'WEBP', quality=70, method=6)
    # The coarser cuts, each averaged off the full painting (BOX), as lossy
    # WebP at the thumbnail's quality: ~250 bytes for all three, where PNG or
    # lossless WebP spend 3x that on fixed chunks around a few dozen pixels.
    cuts = []
    for w in ${JSON.stringify(CUT_WIDTHS.slice(0, -1))}:
        c = im.resize((w, round(w * 14 / 11)), Image.BOX)
        cb = io.BytesIO()
        c.save(cb, 'WEBP', quality=70, method=6)
        cuts.append('data:image/webp;base64,' + base64.b64encode(cb.getvalue()).decode())
    # The TONE is the painting's average over its DETAIL zone (the top 42%,
    # where the subject is) — the quiet zone is dark by rule and would pull
    # every tone to the same brown.
    top = im.crop((0, 0, im.width, round(im.height * 0.42))).resize((1, 1), Image.BOX).getpixel((0, 0))
    out[os.path.splitext(os.path.basename(f))[0]] = {
        't': 'data:image/webp;base64,' + base64.b64encode(b.getvalue()).decode(),
        'k': cuts,
        'c': '#%02x%02x%02x' % top,
    }
print(json.dumps(out))
`;
const thumbs = JSON.parse(execFileSync('python3', ['-c', py, ART]).toString());
const thumbBody = Object.entries(thumbs).map(([k, v]) => `  ${k}: '${v.t}',`).join('\n');
const toneBody = Object.entries(thumbs).map(([k, v]) => `  ${k}: '${v.c}',`).join('\n');
const cutBody = Object.entries(thumbs).map(([k, v]) =>
  `  ${k}: [\n${v.k.map((u) => `    '${u}',`).join('\n')}\n  ],`).join('\n');
fs.writeFileSync(OUT,
  '// GENERATED by tools/art_thumbs.js — do not edit by hand.\n' +
  '// PIXEL RESOLVE placeholders for the dialog paintings (modal_shell.js):\n' +
  `// one ${THUMB_W}×${THUMB_H} inline WebP per assets/art scene piece, and the\n` +
  '// solid TONE each one resolves out of (its detail zone\'s average).\n' +
  `const ART_THUMBS = {\n${thumbBody}\n};\n` +
  `const ART_TONES = {\n${toneBody}\n};\n` +
  '// The coarser resolve cuts, coarse to fine; ART_THUMBS is the last step.\n' +
  `const ART_CUT_WIDTHS = ${JSON.stringify(CUT_WIDTHS)};\n` +
  `const ART_CUTS = {\n${cutBody}\n};\n`);
console.log(`${path.relative(ROOT, OUT)}: ${Object.keys(thumbs).length} thumbnails, ` +
  `${Math.round(fs.statSync(OUT).size / 1024)} KB`);
