#!/usr/bin/env node
// Standalone placement review, generated by the shipping planner and spawn gate.
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const ctx = { addEventListener() {} };
ctx.window = ctx;
vm.createContext(ctx);
for (const name of ['util', 'zone_variant_data', 'terrain', 'zone_variants', 'worldgen', 'cave_areas']) {
  vm.runInContext(fs.readFileSync(path.join(__dirname, '../src', name + '.js'), 'utf8'), ctx, { filename: name + '.js' });
}
const { WorldGen: W, ZoneVariants: V, CaveAreas: C } = ctx;
const N = 64, ty = 20, tileEdgeM = N * W.CELL_M;
const anchorFor = tx => ({ kind: 'grove', gx: tx * 4096 + 32.5 * 64,
  gy: ty * 4096 + 32.5 * 64, originGX: tx * 4096 + 32.5 * 64,
  originGY: ty * 4096 + 32.5 * 64, lx: 32.5 * 64, ly: 32.5 * 64, owned: true, upm: tileEdgeM / 4096 });
let tx = 0;
while (C.select(anchorFor(tx), 1) !== 'spring_cave') {
  if (++tx > 10000) throw new Error('No Spring Cave fixture anchor found');
}
const anchor = anchorFor(tx), a = V.anchorFrame(anchor, { N, tx, ty });
const [cx, cy] = a.local(a.originX, a.originY);
const frame = W.tileFrame({ cellsPerEdge: N }, tx, ty, tileEdgeM);
const cell = (x, y) => (cy + y) * N + cx + x;
function fixture(title, description, setup) {
  const grid = new Uint8Array(N * N).fill(W.T.CAVE_FLOOR);
  const surface = { cellsPerEdge: N, grid: new Uint8Array(N * N).fill(W.T.PARK),
    zone: { anchors: [anchor], coverage: new Uint16Array(N * N).fill(1) } };
  const objects = [], wildplants = [], occupied = new Set();
  const landmark = (kind, dx, dy) => {
    const ix = cx + dx, iy = cy + dy;
    objects.push({ kind, ...frame.centre(ix, iy), _ix: ix, _iy: iy });
    occupied.add(iy * N + ix);
  };
  const sourceMirror = () => {
    const source = { kind: 'chest', id: 'preview_grove_chest', poiClass: 'park',
      _poiAt: `${anchor.lx},${anchor.ly}`, ...frame.centre(cx, cy) };
    surface.genObjects = [source];
    surface.objects = [source];
    objects.push({ kind: 'chest', id: source.id + '_d1', caveOf: source.id,
      poiClass: source.poiClass, depth: 1, ...frame.centre(cx, cy), _ix: cx, _iy: cy });
    occupied.add(cell(0, 0));
  };
  if (setup) setup({ grid, surface, landmark, sourceMirror });
  const plan = C.plan({ surface, grid, N, tx, ty, tileEdgeM, depth: 1, objects, occupied });
  C.apply(plan, grid, objects, wildplants, occupied);
  return { title, description, grid, surface, plan, objects, wildplants };
}
const cases = [
  fixture('01 / Grove chest retained', 'The existing source-linked grove chest starts at the center. Placement moves that same chest onto the dry bank, keeping its identity and rewards.',
    ({ sourceMirror }) => sourceMirror()),
  fixture('02 / Existing chest and stairs', 'A chest beside the pool and stairs in the outer ring keep a one-cell clear approach. Existing landmarks are neither moved nor duplicated.',
    ({ landmark }) => { landmark('chest', 3, -4); landmark('stairs', 5, 6); }),
  fixture('03 / Excluded land', 'Farmland intersects the footprint, so the whole area is declined. The source-linked chest stays at its original center position; no partial edits remain.',
    ({ surface, sourceMirror }) => { sourceMirror(); surface.grid[cell(6, 0)] = W.T.FARMLAND; })
];
if (cases[0].plan.areas.length !== 1 || cases[1].plan.areas.length !== 1 || cases[2].plan.areas.length !== 0) {
  throw new Error('Preview fixtures do not match expected placement outcomes');
}
const placedMirror = cases[0].objects.find(o => o.caveOf);
const declinedMirror = cases[2].objects.find(o => o.caveOf);
if (cases[0].plan.moves.length !== 1 || cases[2].plan.moves.length !== 0 ||
    (placedMirror.x === declinedMirror.x && placedMirror.y === declinedMirror.y) ||
    declinedMirror._ix !== cx || declinedMirror._iy !== cy) {
  throw new Error('Preview source-linked chest movement did not match expected transaction');
}
const esc = s => String(s).replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[ch]);
function draw(row) {
  const size = 24, span = 25, margin = 24;
  const marked = new Map(row.objects.concat(row.wildplants).map(o => [o._iy * N + o._ix, o]));
  let svg = `<svg role="img" aria-label="${esc(row.title)} cave placement grid" viewBox="0 0 ${span * size + margin * 2} ${span * size + margin * 2}">`;
  for (let dy = -12; dy <= 12; dy++) for (let dx = -12; dx <= 12; dx++) {
    const i = cell(dx, dy), x = margin + (dx + 12) * size, y = margin + (dy + 12) * size;
    const terrain = row.grid[i], excluded = row.surface.grid[i] === W.T.FARMLAND;
    const color = excluded ? '#7b3f43' : terrain === W.T.WATER ? '#397b92' : terrain === W.T.CAVE_WALL ? '#777d83' : row.plan.reserved.has(i) ? '#4b493c' : '#252a2b';
    const o = marked.get(i);
    const label = excluded ? 'Excluded farmland' : terrain === W.T.WATER ? 'Pool' : terrain === W.T.CAVE_WALL ? 'Rock source' : row.plan.reserved.has(i) ? 'Reserved dry floor' : 'Ordinary cave floor';
    svg += `<g><title>${esc(label + (o ? ' / ' + (o.crop || o.kind) : '') + ' (' + dx + ', ' + dy + ')')}</title><rect x="${x}" y="${y}" width="24" height="24" fill="${color}" stroke="#151b1c" stroke-width=".6"/>`;
    if (o?.crop === 'mushroom') svg += `<path d="M${x+5} ${y+12}a7 7 0 0 1 14 0z" fill="#c6a3d0"/><rect x="${x+10}" y="${y+12}" width="4" height="6" fill="#eadce9"/>`;
    else if (o?.kind === 'mineralrock') svg += `<path d="M${x+5} ${y+17}l2-10 8-2 5 9-4 5z" fill="#aaa9a0" stroke="#d2d2c6"/>`;
    else if (o) svg += `<text x="${x+12}" y="${y+17}" text-anchor="middle" fill="#ffdc8a" font-size="16" font-weight="bold">${o.kind === 'chest' ? 'C' : 'S'}</text>`;
    if (excluded) svg += `<text x="${x+12}" y="${y+17}" text-anchor="middle" fill="#ffd1d1" font-size="15">×</text>`;
    svg += '</g>';
  }
  return svg + '</svg>';
}
const cards = cases.map(row => {
  const water = [...row.plan.terrain.values()].filter(t => t === W.T.WATER).length;
  const status = row.plan.diagnostics.map(d => d.status + (d.reason ? ': ' + d.reason : '')).join(', ');
  return `<section><h2>${esc(row.title)}</h2><p>${esc(row.description)}</p>${draw(row)}<p class="status">${esc(status)}</p><dl><div><dt>Pool cells</dt><dd>${water}</dd></div><div><dt>Mushrooms</dt><dd>${row.plan.wildplants.length}</dd></div><div><dt>Rocks</dt><dd>${row.plan.objects.length}</dd></div><div><dt>Reserved cells</dt><dd>${row.plan.reserved.size}</dd></div><div><dt>Chest moves</dt><dd>${row.plan.moves.length}</dd></div></dl></section>`;
}).join('\n');
const output = path.resolve(process.argv[2] || '/tmp/terracart-spring-preview.html');
fs.writeFileSync(output, `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Spring Cave — D1 placement review</title><style>
*{box-sizing:border-box}body{margin:0;padding:40px;background:#151b1c;color:#e9ede7;font:16px/1.5 system-ui,sans-serif}main{max-width:1800px;margin:auto}.eyebrow{color:#b5b795;letter-spacing:.12em;font-size:12px}h1{font-size:clamp(28px,4vw,46px);margin:8px 0}header p{max-width:900px;color:#bbc5c0}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px;margin-top:28px}section{background:#202728;border:1px solid #394142;border-radius:12px;padding:20px}h2{font-size:21px;margin:0}section>p{font-size:14px;color:#bdc8c1;min-height:66px}svg{display:block;width:100%;height:auto}.status{font-family:monospace!important;color:#e1d994!important;min-height:0!important}dl{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}dt{font-size:11px;color:#9ea9a2}dd{margin:0;font-size:22px}.legend{display:flex;flex-wrap:wrap;gap:18px;font-size:13px;margin-top:22px}.key{width:13px;height:13px;display:inline-block;margin-right:7px;vertical-align:-2px}.note{font-size:13px;color:#9faa9f;margin-top:26px}@media(max-width:1000px){.cards{grid-template-columns:1fr}body{padding:22px}section>p{min-height:0}svg{max-width:680px;margin:auto}}
</style><main><header><div class="eyebrow">TERRACART / CAVE LEVEL 1</div><h1>Spring Cave placement review</h1><p>A central pool, a dry bank, mushroom and stone rings, and four clear approaches. These schematic grids come directly from <code>CaveAreas.plan</code> and <code>CaveAreas.apply</code>, using the shared surface anchor frame and the real world-generation spawn gate.</p></header><div class="legend"><span><i class="key" style="background:#397b92"></i>Water</span><span><i class="key" style="background:#777d83"></i>Rock source</span><span><i class="key" style="background:#4b493c"></i>Reserved dry floor</span><span><i class="key" style="background:#252a2b"></i>Ordinary cave floor</span><span><i class="key" style="background:#c6a3d0"></i>Mushroom</span><span><i class="key" style="background:#aaa9a0"></i>Mineable rock</span><span>C / Existing chest</span><span>S / Existing stairs</span><span><i class="key" style="background:#7b3f43"></i>Excluded land</span></div><div class="cards">${cards}</div><p class="note">Placement schematic, not a game screenshot. Each square is one game cell. Hover a cell for its contents and offset. Synthetic fixtures isolate placement behavior; world selection remains deterministic. Anchor: ${esc(V.identity(anchor))}. Encounters are a later phase.</p></main></html>`);
console.log(output);
console.log(cases.map(row => `${row.title}: ${JSON.stringify(row.plan.diagnostics)}, ${row.plan.reserved.size} reserved cells`).join('\n'));
