#!/usr/bin/env python3
"""Render a self-contained, read-only comparison of existing nature sprites.

Requires Pillow. Reserve assets are ignored and normally live in the main checkout.
python3 tools/preview_nature_candidates.py --reserve-root /home/claude/terracart/unused_art
"""
import argparse
import base64
import html
import io
import json
import math
import pathlib
import re
import subprocess

from PIL import Image, ImageDraw

ROOT = pathlib.Path(__file__).resolve().parents[1]
PROPS = 'assets/Objects/Wilderness/Props.png'
VERDANT = 'unused_art/verdant-props-tileset-16x16/tiles/16x16/'
FANTASY = 'unused_art/The Fan-tasy Tileset (Free) 1.5.7/The Fan-tasy Tileset (Free)/Art/'
PROVENANCE = {
    'generated': 'Existing generated placeholder art, identified in assets/Objects/Generated/README.md as image-model output downsampled to pixel sprites. Included from the earlier sprite audit for review; no new art is generated by this tool.',
    'shipped': 'Existing repository art; these source files are already shipped with the game. A separate pack licence was not located in this audit.',
    'reserve': 'art-source/sprites/README.md identifies Fantasy Mushroom.png as the former mushroom sheet, retained for future selection and no longer preloaded. A separate pack licence was not located.',
    'verdant': 'Core Systems Asset Factory, 2026. Local unused_art/verdant-props-tileset-16x16/LICENSE.txt permits game use and modification with optional attribution. The origin statement describes programmatic art made from hand-authored rules, without an image-generation model.',
    'fantasy': 'The Fan-tasy Tileset Free 1.5.7. Its local Free Trial Guide lists the included trees and props. An explicit licence grant was not located in the local PDFs.',
}


def prop(ident, title, group, frame, note, current=False, recommended=False):
    return dict(id=ident, title=title, group=group, path=PROPS,
                rect=(frame % 22 * 16, frame // 22 * 16, 16, 16),
                frame=frame, note=note, current=current,
                recommended=recommended, provenance='shipped')


def candidates():
    rows = [
        prop('grass-current', 'Current long grass', 'grass', 10, 'Bright upright green tuft.', current=True),
        prop('grass-green', 'Pale green tuft', 'grass', 32, 'Closest match: the existing tuft silhouette in a lighter green.'),
        prop('grass-golden', 'Golden tuft', 'grass', 54, 'Warm, dry-grass colour variant of the same upright tuft.'),
        dict(id='grass-fern', title='Low woodland fern', group='grass', path=VERDANT+'fern.png', rect=(0, 0, 16, 16), provenance='verdant', note='Complete low fern, with subdued greens and a broad, symmetrical spread.'),
        dict(id='grass-leafy', title='Leafy green sprig', group='grass', path=FANTASY+'Props/Plant_2.png', rect=(0, 0, 15, 11), provenance='fantasy', recommended=True, note='A distinct alternative: loose green leaves around a central stem. Softer shading than the current grass.'),
        prop('mushroom-current', 'Current surface mushroom', 'mushrooms', 35, 'Small lime-green cap and pale stem.', current=True),
        prop('mushroom-cave-a', 'Current cave mushroom A', 'mushrooms', 127, 'The first luminous blue underground variant; static art shown without its runtime light.', current=True),
        prop('mushroom-cave-b', 'Current cave mushroom B', 'mushrooms', 128, 'The second luminous blue underground variant; static art shown without its runtime light.', current=True),
        prop('mushroom-red', 'Red spotted toadstool', 'mushrooms', 13, 'Best style match: a clear red cap with pale spots, in the same 16 × 16 source format.', recommended=True),
        prop('mushroom-brown', 'Brown woodland cap', 'mushrooms', 55, 'A plain, dark brown cap and short stem. More subdued than the current green.'),
        prop('mushroom-cluster', 'Peach mushroom cluster', 'mushrooms', 108, 'Several connected orange-peach caps make a fuller, varied cluster.'),
        dict(id='mushroom-verdant', title='Plain brown pair', group='mushrooms', path=VERDANT+'mushrooms.png', rect=(0, 0, 16, 16), provenance='verdant', note='Two simple brown mushrooms, with restrained shading and no spots.'),
        dict(id='mushroom-reserve-red', title='Tall red pair', group='mushrooms', path='art-source/sprites/Fantasy Mushroom.png', rect=(32, 0, 32, 48), provenance='reserve', note='Complete paired mushrooms from the reserve sheet. The whole sprite needs a 32 × 48 rectangle; a 32 × 32 grid would clip it. Giant mushroom trees are excluded here.'),
    ]
    registry = json.loads(subprocess.check_output(['node', str(ROOT/'tools/preview_variant_art.js')], cwd=ROOT))
    shrub = registry['crops']['shrub']
    source = registry['assets'][shrub['sheet']]
    with Image.open(ROOT/source['path']) as sheet:
        columns = sheet.width // source['frameWidth']
    fw, fh, frame = source['frameWidth'], source['frameHeight'], shrub['frame']
    rows.extend([
        dict(id='bush-current', title='Current shrub', group='bushes', current=True, path=source['path'], rect=(frame % columns*fw, frame//columns*fh, fw, fh), frame=frame, render_scale=shrub['scale'], provenance='shipped', note='Current CROP_SPRITE.shrub, resolved through the live asset registry. Compact rounded teal foliage with a dark edge; keep its silhouette and consider an olive palette.'),
        dict(id='bush-green', title='Green rounded shrub', group='bushes', path='assets/Objects/Wilderness/bushes.png', rect=(48, 0, 48, 32), frame=1, provenance='shipped', recommended=True, note='Strongest alternate style fit: the same complete rounded silhouette and dark outline. Recolour its lime greens toward moss and olive for the story-art palette.'),
        dict(id='bush-golden', title='Golden autumn shrub', group='bushes', path='assets/Objects/Wilderness/bushes.png', rect=(96, 0, 48, 32), frame=2, provenance='shipped', note='Same chunky silhouette; orange-gold foliage is a strong dryland or autumn exception. Muted ochre highlights would better match the paintings.'),
        dict(id='bush-verdant', title='Low dark woodland bush', group='bushes', path=VERDANT+'bush.png', rect=(0, 0, 16, 16), provenance='verdant', note='Quiet olive palette and a complete low mound. Tiny, flat and sparsely shaded beside the outlined characters: better for ambient undergrowth than the main collectible shrub.'),
        dict(id='bush-emerald', title='Soft emerald shrub', group='bushes', path=FANTASY+'Trees and Bushes/Bush_Emerald_1.png', rect=(0, 0, 40, 29), provenance='fantasy', note='Complete multi-lobed bush, included for comparison. Soft mint shading and weak contour do not match the Cyan characters; a palette change alone would not fix its style.'),
        dict(id='bush-hedge-end', title='Clipped hedge end', group='bushes', path='assets/Objects/Generated/hedge_end.png', rect=(0, 0, 16, 16), provenance='generated', note='Requested from the sprite audit: a complete rounded hedge block with a strong dark contour. Excellent compact shape for formal gardens; shift bright lime toward olive to match the story paintings.'),
        dict(id='ruin-pillar-c', title='Weathered stone grave marker', group='graves', path='assets/Objects/Generated/pillar_c.png', rect=(0, 0, 16, 16), provenance='generated', recommended=True, note='Requested sprite-audit candidate. Complete short pillar, with a chunky dark edge and warm stone ramp: a strong shape and palette match for chibi-scale ruins.'),
        dict(id='pot-intact', title='Intact clay pot', group='containers', path='assets/Objects/Generated/pot.png', rect=(0, 0, 16, 16), provenance='generated', note='Intact lootable pot: a barrel variant with the same low-grade loot and restock.'),
        dict(id='ruin-pot-smashed', title='Broken clay pot', group='containers', path='assets/Objects/Generated/pot_smashed.png', rect=(0, 0, 16, 16), provenance='generated', note='Sprite-audit candidate with a clear shattered silhouette and dark outline. Rust-red pottery suits the paintings; useful as sparse ruins dressing, not a replacement for every stone.'),
        dict(id='ruin-broken-column', title='Broken fluted column', group='ruins', path=VERDANT+'broken_column.png', rect=(0, 0, 16, 16), provenance='verdant', note='Complete pale column fragment. The stepped geometry reads clearly; darken its outer edge and warm the greys if adopting alongside the character sprites.'),
        dict(id='ruin-rubble-pile', title='Loose rubble pile', group='ruins', path=VERDANT+'rubble_pile.png', rect=(0, 0, 16, 16), provenance='verdant', note='Complete low stone heap with separated block shapes. Muted greys fit ruins, but its weak outline needs more contrast at tiny scale.'),
        dict(id='ruin-masonry', title='Broken masonry mound', group='ruins', path=VERDANT+'rubble_masonry.png', rect=(0, 0, 16, 16), provenance='verdant', note='Low remnants of stone and brick, with warm brown accents. Best as a masonry-specific ruin variant; a stronger dark contour would match the characters better.'),
    ])
    for kind, path in [('maple', 'assets/Objects/Maple Tree.png'), ('pine', 'assets/Objects/Wilderness/Pine Tree.png'), ('birch', 'assets/Objects/Wilderness/Birch Tree.png'), ('mahogany', 'assets/Objects/Wilderness/Mahogany Tree.png')]:
        rows.append(dict(id='tree-current-'+kind, title='Current '+kind, group='trees', path=path, rect=(96, 0, 32, 48), frame=3, current=True, provenance='shipped', note='The complete mature tree, using runtime frame 3.'))
    for ident, title, path, rect, note in [
        ('tree-tall-green', 'Open green broadleaf', 'assets/Objects/Tree.png', (64, 0, 32, 48), 'Best style match: a branching green tree with an open trunk and a flatter crown than maple.'),
        ('tree-tall-teal', 'Open teal broadleaf', 'assets/Objects/Tree.png', (64, 48, 32, 48), 'A darker teal palette on the same complete branching tree.'),
        ('tree-autumn-birch', 'Red autumn birch', 'assets/Objects/Wilderness/Birch Tree.png', (128, 0, 32, 48), 'A red autumn crown above a white birch trunk, in the existing mature-tree footprint.'),
        ('tree-emerald-broadleaf', 'Soft emerald broadleaf', FANTASY+'Trees and Bushes/Tree_Emerald_2.png', (0, 0, 46, 63), 'Whole tree with softer foliage and a broad warm trunk. Larger source pixels require a deliberate runtime scale.'),
        ('tree-emerald-pine', 'Wide emerald evergreen', FANTASY+'Trees and Bushes/Tree_Emerald_1.png', (0, 0, 64, 63), 'Whole evergreen with wide, layered boughs. A softer style and wider silhouette than current pine.'),
    ]:
        rows.append(dict(id=ident, title=title, group='trees', path=path, rect=rect, note=note, provenance='fantasy' if path.startswith('unused_art/') else 'shipped', recommended=ident == 'tree-tall-green'))
    return rows


def crop(row, reserve):
    path = reserve / row['path'][len('unused_art/'):] if row['path'].startswith('unused_art/') else ROOT / row['path']
    with Image.open(path) as source:
        image = source.convert('RGBA')
    x, y, w, h = row['rect']
    assert 0 <= x < x+w <= image.width and 0 <= y < y+h <= image.height, path
    image = image.crop((x, y, x+w, y+h))
    assert image.getbbox(), f'Blank crop: {row["id"]}'
    return image


def data_uri(image):
    output = io.BytesIO()
    image.save(output, format='PNG')
    return 'data:image/png;base64,' + base64.b64encode(output.getvalue()).decode()


def current_crop_scales():
    """Fail clearly if this comparison's current source-frame references drift."""
    source = (ROOT / 'src/items.js').read_text()
    scales = {}
    for kind, frame in [('longgrass', 10), ('mushroom', 35)]:
        body = re.search(r'\b'+kind+r':\s*\{([^}]+)\}', source).group(1)
        assert re.search(r"sheet:\s*'props'", body) and re.search(r'frame:\s*'+str(frame)+r'\b', body), kind
        scales[kind] = float(re.search(r'scale:\s*([\d.]+)', body).group(1))
        if kind == 'mushroom':
            assert re.search(r'caveFrames:\s*\[127,\s*128\]', body)
    return scales


def palette_chips(combo, palette):
    return '<div class="target-palette" aria-label="Target colours">' + ''.join(
        f'<span class="target-colour" title="{html.escape(palette[key]["name"])} {palette[key]["hex"]}">'
        f'<i style="background:{palette[key]["hex"]}"></i><small>{html.escape(palette[key]["name"])}</small></span>'
        for key in combo['colours']) + '</div>'


def recolour_comparison(image, combo):
    source = data_uri(image)
    zoom = max(1, min(4, 96 // image.width, 144 // image.height))
    width, height = image.width * zoom, image.height * zoom
    return (f'<div class="colour-comparison"><figure><div><img src="{source}" alt="Original colours" width="{width}" height="{height}"></div><figcaption>Original</figcaption></figure>'
            f'<figure><div><canvas data-recolour="{combo["id"]}" data-source="{source}" aria-label="{html.escape(combo["role"])} proposed recolour" style="width:{width}px;height:{height}px"></canvas></div><figcaption>Proposed</figcaption></figure></div>')


def combo_annotation(combo, palette, image, default=False):
    label = 'DEFAULT + RECOLOUR' if default else 'USAGE VARIANT'
    return (f'<div class="recipe {"default-recipe" if default else "variant-recipe"}">'
            f'<b>{label} · {html.escape(combo["role"])}</b>'
            f'<p class="usage">{html.escape(combo["usage"])}</p>'
            + recolour_comparison(image, combo) + palette_chips(combo, palette)
            + f'<p>{html.escape(combo["treatment"])}</p></div>')


def render(reserve, output):
    output.mkdir(parents=True, exist_ok=True)
    rows = candidates()
    scales = current_crop_scales()
    direction = json.loads((ROOT/'docs/art/art-direction.json').read_text())
    assessments = direction['recommendations']
    assert set(assessments) == {row['id'] for row in rows}, 'Every candidate needs a current art-direction assessment'
    plan = direction['spritePlan']
    palette = {p['id']: p for p in direction['palette']}
    defaults = {c['candidate']: c for c in plan['defaults']}
    variants = {}
    candidate_ids = {row['id'] for row in rows}
    for combo in plan['defaults'] + plan['variants']:
        assert combo['candidate'] in candidate_ids, combo['candidate']
        assert all(key in palette for key in combo['colours']), combo['id']
    assert len(defaults) == len(plan['defaults']), 'Duplicate default candidate'
    for combo in plan['variants']:
        variants.setdefault(combo['candidate'], []).append(combo)
    cards = {}
    images = {}
    for row in rows:
        im = images[row['id']] = crop(row, reserve)
        bounds = im.getbbox()
        row['visible_bounds'] = bounds
        uri = data_uri(im)
        is_tree = row['group'] == 'trees'
        is_bush = row['group'] == 'bushes'
        shrub = next(r for r in rows if r['id'] == 'bush-current')
        target_h = 48 if is_tree else shrub['rect'][3]*shrub['render_scale'] if is_bush else 24 if row['group'] in ('ruins', 'graves', 'containers') else 16 * scales['longgrass' if row['group'] == 'grass' else 'mushroom']
        target_w = 48 if is_tree else shrub['rect'][2]*shrub['render_scale'] if is_bush else 24
        ratio = min(target_h / im.height, target_w / im.width)
        assessment = row['assessment'] = assessments[row['id']]
        row.pop('recommended', None)
        row['defaultCombo'] = defaults.get(row['id'])
        row['usageVariants'] = variants.get(row['id'], [])
        recipes = (combo_annotation(row['defaultCombo'], palette, im, True) if row['defaultCombo'] else '')
        recipes += ''.join(combo_annotation(c, palette, im) for c in row['usageVariants'])
        if not recipes:
            recipes = '<div class="recipe unused-recipe"><b>NOT SELECTED</b><p>Retained for comparison; use the selected default or a named usage variant.</p></div>'
        selection = 'selected-default' if row['defaultCombo'] else 'selected-variant' if row['usageVariants'] else 'not-selected'
        badge = ('CURRENT · ' if row.get('current') else '') + assessment['decision'].upper()
        assessment_html = '<div class=assessment><b>Style: '+html.escape(assessment['style'])+'</b><br>Palette: '+html.escape(assessment['palette'])+'<br>Use: '+html.escape(assessment['context'])+'<p>'+html.escape(assessment['note'])+'</p></div>'
        if row['defaultCombo']:
            badge = 'SELECTED DEFAULT + RECOLOUR' + (' · KEEP CURRENT SHAPE' if row.get('current') else '')
        elif row['usageVariants']:
            badge = 'USAGE-SPECIFIC VARIANT' + (' · CURRENT ART' if row.get('current') else '')
        else:
            badge = 'NOT SELECTED · ' + assessment['decision'].upper()
        native_zoom = 3 if is_tree else 4
        card = f'''<article id="{row['id']}" class="{selection}"><div class="badge">{badge}</div><h3>{html.escape(row['title'])}</h3><code>{row['id']}</code>
<div class="native"><img alt="{html.escape(row['title'])}" src="{uri}" width="{im.width*native_zoom}" height="{im.height*native_zoom}"></div>
<div class="caption">Native frame ×{native_zoom} · {im.width} × {im.height} px</div>
<div class="small"><img alt="Small comparison: {html.escape(row['title'])}" src="{uri}" style="width:{im.width*ratio:.3f}px;height:{im.height*ratio:.3f}px"></div>
<div class="caption">{'48 px frame-height fit' if is_tree else f'{target_h:.3f} px frame-height fit'}</div>
{recipes}{assessment_html}<details><summary>Source rectangle &amp; provenance</summary><p class="path">{html.escape(row['path'])}</p><p>x, y, width, height: <code>{row['rect']}</code>{'; frame '+str(row['frame']) if 'frame' in row else ''}. Visible bounds: <code>{bounds}</code>.</p><p>{html.escape(PROVENANCE[row['provenance']])}</p></details></article>'''
        cards.setdefault(row['group'], []).append(card)
    row_by_id = {row['id']: row for row in rows}
    default_cards = []
    for combo in plan['defaults']:
        row = row_by_id[combo['candidate']]
        default_cards.append(f'<div class="default-pick">'
            f'<h3>{html.escape(combo["role"])}</h3><a href="#{row["id"]}">{html.escape(row["title"])}</a>'
            + recolour_comparison(images[row['id']], combo) + palette_chips(combo, palette) + f'<p>{html.escape(combo["treatment"])}</p></div>')
    default_summary = '<section id="defaults"><h2>Default sprite + recolour combinations</h2><p>'+html.escape(plan['note'])+'</p><div class="grid defaults-grid">'+''.join(default_cards)+'</div></section>'
    variant_links = ''.join(f'<a href="#{c["candidate"]}">{html.escape(c["role"])}</a>' for c in plan['variants'])
    default_summary += '<section id="usage-variants"><h2>Variants for specific uses</h2><p>Use these only for the named setting or role. Their cards specify the sprite, target colours and any extra contour work.</p><div class="variant-links">'+variant_links+'</div></section>'
    sections = ''.join(f'<section id="{group}"><h2>{title}</h2><p>{intro}</p><div class="grid">{"".join(cards[group])}</div></section>' for group, title, intro in [
        ('grass', 'Grass & ferns', 'Collectible tufts and ferns, rather than ground terrain. Default: keep the current chunky tuft and recolour to olive. Dry grass and low fern are usage-specific variants. The soft leafy sprig is no longer recommended for main-world grass.'),
        ('mushrooms', 'Mushrooms', 'Surface and both cave looks are shown first. Default: red spotted cap recoloured to muted brick and cream. Brown woodland caps and warm clusters are local variants. Blue cave caps remain a special-area exception.'),
        ('bushes', 'Bushes', 'Current shrub and five complete alternatives, including the requested hedge_end.png. Default: hedge_end.png with olive colours. Reuse it with brighter colours for restored hedges; rounded shrubs have specific woodland or sacred uses. Small views fit the current shrub frame dimensions and runtime scale.'),
        ('trees', 'Whole trees', 'The four current mature trees precede five complete alternatives. Default: tree-tall-green with olive foliage and warm bark. Teal belongs in restored or sacred groves; autumn red needs a rustic rust/ochre treatment.'),
        ('graves', 'Grave marker', 'The weathered stone pillar is the grave marker. Its proposed colour treatment stays in the rustic stone palette.'),
        ('containers', 'Clay pot · intact and broken', 'One lootable container with two states. Mostly empty; occasional low-grade coins, apple or supply, using barrel rules. The broken sprite appears after opening, not as independent rubble.'),
        ('ruins', 'Ruins props', 'A focused shortlist from the sprite audit and local reserve: complete pillars, broken pottery and rubble. Masonry, low rubble and pale sacred columns have specific secondary uses. The pillar grave and lootable pot are shown separately above. These annotations do not change runtime placement. Small views use a shared 24 px frame height.'),
    ])
    page = f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Nature art candidates</title><style>
*{{box-sizing:border-box}}body{{margin:0;background:#14231f;color:#e7efe8;font:16px/1.5 system-ui,sans-serif}}main{{max-width:1440px;margin:auto;padding:28px}}h1{{font-size:36px;margin-bottom:8px}}h2{{margin-top:48px}}h3{{margin:8px 0;font-size:18px}}p{{color:#c3d3c7}}a{{color:#e6c780}}nav{{display:flex;gap:22px;flex-wrap:wrap}}.grid{{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,260px),1fr));gap:16px}}article{{background:#1e332b;border:1px solid #48614e;border-radius:14px;padding:18px;min-width:0}}.ground-control{{display:inline-block;padding:10px 14px;background:#283627;border-radius:8px}}.ground-control select{{margin-left:12px;padding:6px;background:#14231f;color:#e6d7a3;border:1px solid #777462}}.colour-comparison{{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:14px 0}}.colour-comparison figure{{margin:0;min-width:0;text-align:center}}.colour-comparison figure>div{{min-height:150px;background:var(--preview-ground,#7f9174);display:flex;align-items:center;justify-content:center;border-radius:5px}}.colour-comparison img,.colour-comparison canvas{{image-rendering:pixelated;object-fit:contain;max-width:100%}}.colour-comparison figcaption{{font-size:12px;margin-top:5px}}.selected-default{{border:2px solid #c4b06a}}.selected-variant{{border-color:#6b90ac}}.not-selected{{border-style:dashed}}.defaults-grid{{grid-template-columns:repeat(3,minmax(0,1fr))}}.default-pick{{padding:18px;background:#283627;border:1px solid #c4b06a;border-radius:12px;min-width:0}}.default-pick>img{{float:right;width:64px;height:64px;margin-left:8px}}.default-pick p{{font-size:14px}}.target-palette{{display:flex;flex-wrap:wrap;gap:7px;clear:both;margin:12px 0}}.target-colour{{width:51px;text-align:center;display:block}}.target-colour i{{display:block;width:38px;height:25px;margin:auto;border:1px solid #a5a569}}.target-colour small{{display:block;font-size:10px;line-height:1.25;margin-top:4px;color:#c3d3c7}}.recipe{{padding:12px;margin-top:16px;background:#14231f;border-radius:6px;font-size:13px}}.default-recipe{{border-left:3px solid #c4b06a}}.variant-recipe{{border-left:3px solid #6b90ac}}.recipe b{{font-size:12px;color:#e6d7a3}}.recipe .usage{{margin-top:5px}}.variant-links{{display:flex;gap:10px;flex-wrap:wrap}}.variant-links a{{background:#1e332b;border:1px solid #48614e;border-radius:6px;padding:6px 10px;font-size:13px}}section,article{{scroll-margin-top:90px}}.assessment{{border-left:3px solid #a5a569;padding-left:10px;margin:16px 0;font-size:13px}}.badge{{font-size:11px;letter-spacing:1px;color:#e5cb81}}code{{font-size:12px;overflow-wrap:anywhere}}.native{{height:206px;display:flex;align-items:center;justify-content:center;margin-top:18px;background:#7f9174;border-radius:8px}}img{{image-rendering:pixelated;object-fit:contain}}.small{{height:64px;display:flex;align-items:center;justify-content:center;margin-top:16px;background:#7f9174;border:1px dashed #a5b396;border-radius:8px}}.caption{{font-size:12px;color:#aebfb2;text-align:center;margin-top:5px}}details{{font-size:12px;border-top:1px solid #48614e;padding-top:12px}}summary{{cursor:pointer}}.path{{overflow-wrap:anywhere}}.intro{{max-width:1000px}}@media(max-width:900px){{.defaults-grid{{grid-template-columns:repeat(2,minmax(0,1fr))}}}}@media(max-width:600px){{.defaults-grid{{grid-template-columns:1fr}}main{{padding:16px}}h1{{font-size:28px}}}}
</style><main><nav><a href="#defaults">Selected defaults</a><a href="#usage-variants">Usage variants</a><a href="art-direction.html">Palette and style rules</a><a href="index.html">Zone previews</a><a href="#grass">Grass</a><a href="#mushrooms">Mushrooms</a><a href="#bushes">Bushes</a><a href="#trees">Trees</a><a href="#graves">Grave</a><a href="#containers">Clay pot</a><a href="#ruins">Ruins</a><a href="nature-contact.png">Contact sheet</a></nav><h1>Selected nature and ruins art</h1><p id="recolour-status">Original → Proposed: live palette swaps. Any outline cleanup remains pending.</p><label class="ground-control">Preview ground <select id="preview-ground"><option value="#7f9174">Light grass</option><option value="#26342a">Dark forest</option><option value="#4c3018">Brown earth</option></select></label><div class="intro"><p>Revised for the current chibi pixel characters and story-art palette. Natural and pre-restoration objects stay muted and rustic; restored assets and special or sacred areas may deliberately use brighter or cooler colours. Original and Proposed comparisons now show the palette swaps. The proposed colours preserve the source pixel positions and transparency; game textures are not recoloured. Grave and pot roles follow the corrected assignments.</p><p>The large view preserves native pixels at an integer zoom. The small view fits each frame into a common category height, capped in width. Current grass uses CROP_SPRITE scale {scales['longgrass']}; all current mushrooms use {scales['mushroom']}. Their small views therefore match those frame scales. Tree comparisons use a common 48 px frame height, not runtime camera zoom. Source margins are retained.</p></div>{default_summary}{sections}<p>All {len(rows)} sprite crops are embedded in this page. Coordinates are source pixels (x, y, width, height). Whole silhouettes were visually checked against their sheets. Local provenance is listed per card; colour previews only; no contours have been redrawn.</p></main></html>'''
    payload = {'palette': direction['palette'], 'combos': plan['defaults'] + plan['variants']}
    script = (ROOT/'tools/nature_recolour.js').read_text()
    page = page.replace('</html>', '<script id="recolour-data" type="application/json">'+json.dumps(payload).replace('<', '\\u003c')+'</script><script>'+script+'</script></html>')
    (output / 'nature-art.html').write_text(page)
    (output / 'nature-candidates.json').write_text(json.dumps(rows, indent=2)+'\n')
    columns, cell_w, cell_h = 5, 240, 260
    contact = Image.new('RGB', (columns*cell_w, math.ceil(len(rows)/columns)*cell_h), '#819477')
    draw = ImageDraw.Draw(contact)
    for index, row in enumerate(rows):
        x, y = (index % columns)*cell_w, (index//columns)*cell_h
        im = images[row['id']]
        zoom = min(3 if row['group'] == 'trees' else 6, 190//im.height)
        enlarged = im.resize((im.width*zoom, im.height*zoom), Image.Resampling.NEAREST)
        contact.paste(enlarged, (x+(cell_w-enlarged.width)//2, y+30+(190-enlarged.height)//2), enlarged)
        draw.text((x+8, y+8), 'DEFAULT + RECOLOUR' if row['defaultCombo'] else 'USAGE VARIANT' if row['usageVariants'] else 'NOT SELECTED', fill='#203027')
        draw.text((x+8, y+226), row['id'], fill='#13201a')
        draw.text((x+8, y+242), str(tuple(row['rect'])), fill='#13201a')
    contact.save(output / 'nature-contact.png')
    print(f'{len(rows)} verified nonempty crops: {output / "nature-art.html"}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--reserve-root', type=pathlib.Path, default=ROOT/'unused_art')
    parser.add_argument('--output', type=pathlib.Path, default=pathlib.Path.home()/'.artifacts/zone-variants')
    args = parser.parse_args()
    render(args.reserve_root, args.output)
