#!/usr/bin/env node
// Compile the reviewed JSON table for synchronous browser script loading.
// Run --write after editing docs/zone-variants.json; --check is read-only.
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const source = path.join(root, 'docs/zone-variants.json');
const target = path.join(root, 'src/zone_variant_data.js');
const data = JSON.parse(fs.readFileSync(source, 'utf8'));
const ids = new Set();
const types = new Set(['seeded_scatter', 'repeat_motif', 'line_grid', 'bounded_line_grid', 'concentric_rings']);
function fail(message) { throw new Error(`zone variants: ${message}`); }
function material(value) {
  if (value && Array.isArray(value.cycle)) return value.cycle.forEach(material);
  if (!data.materials[value]) fail(`unknown material ${JSON.stringify(value)}`);
}
for (const row of data.variants) {
  if (ids.has(row.id)) fail(`duplicate id ${row.id}`);
  ids.add(row.id);
  if (!['grove', 'stones', 'tar'].includes(row.zone)) fail(`unknown zone ${row.zone}`);
  if (!(row.weight > 0)) fail(`invalid weight ${row.id}`);
  const b = row.background;
  if (!types.has(b.type)) fail(`unknown layout ${b.type}`);
  const seen = new Set();
  for (const slot of b.slots || []) {
    const key = slot.at.join(',');
    if (seen.has(key)) fail(`duplicate background slot ${row.id}/${key}`);
    seen.add(key);
    material(slot.material);
  }
  for (const field of ['horizontalMaterial', 'verticalMaterial', 'intersectionMaterial']) {
    if (b[field]) material(b[field]);
  }
  if (b.plotCenters) material(b.plotCenters.material);
  if (b.gapScatter) {
    material(b.gapScatter.material);
    if (b.type !== 'repeat_motif' || !(b.gapScatter.chance > 0 && b.gapScatter.chance <= 1)) fail(`gap scatter ${row.id}`);
  }
  for (const id of Object.keys(b.materialDensity)) material(id);
  for (const id of Object.keys(b.hazardDensity || {})) material(id);
  for (const pattern of [row.poi, row.poi.whenInsideBuilding]) {
    for (const slot of pattern ? pattern.slots : []) material(slot.material);
  }
  material(row.finds.material);
  if (row.connection.material) material(row.connection.material);
  if (row.finds.count !== row.finds.targets.length) fail(`find count ${row.id}`);
  if (!b.poiOrigin.cell.every(Number.isInteger)) fail(`POI origin ${row.id}`);
  if (row.zone === 'tar' && row.guards.mode !== 'none') fail(`tar guard ${row.id}`);
}
const output = '// Generated by tools/zone_variant_data.js from docs/zone-variants.json. Do not edit.\n' +
  '(function (root) {\n  root.ZoneVariantData = ' + JSON.stringify(data, null, 2) + ';\n})(typeof window !== "undefined" ? window : globalThis);\n';
if (process.argv.includes('--write')) {
  fs.writeFileSync(target, output);
  console.log(`Generated ${data.variants.length} zone variants.`);
} else {
  if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== output) {
    fail('generated data is stale; run node tools/zone_variant_data.js --write');
  }
  console.log(`${data.variants.length} zone variants match their canonical JSON.`);
}
