// Approved enemy roster: actual shared stats, before Elite and player-side difficulty.
// Combat, art, behaviour and spawn eligibility resolve the same row. No cave doubling.
// CAVE WINDOWS ARE TWO LEVELS (owner, Oct 2026): a kind's cave.minDepth..maxDepth
// spans its introduction level and the next, so each level down reads as a
// new population. Only the deepest kind of each habitat family (lich,
// minotaur, armoured_demon, hell_brute, the dragon) is open-ended, so the
// levels past 9 stay peopled; the three demons all sit on level 9, where the
// dragon story takes its fire back (dragon_story.js). minDepth is also a
// kind's introduction depth for elite loot (combat.js eliteRollBonus).
// Trolls are the explicit exception: they inhabit level 3 only.
// PACES (owner, Oct 2026): every goblin and orc row moves at TWICE its first
// figure (a goblin 7 m/s, an orc 3), and the bats sit on the wild speed
// ceiling (creature_ai.js WILD_SPEED_CEILING_MPS, 10 — twice 5.5 would clear
// it, and no cap is ever added on top of a row). Retune the row, never a lane.
(function (root) {
  'use strict';
  // Blight uses one damage-rate contract; each carrier can override its radius.
  const BLIGHT_AURA = {"source":"Potion of Blight","rawDps":2,"mitigationPacketSeconds":1,"healsSelf":false,"stacks":"Independent sources add; at most one aura contribution per enemy per target.","damageType":"energy","rule":"Mitigate a one-second damage packet with Combat.mitigate, then accumulate the resulting rate \u00d7 dt. Never apply the minimum-hit floor per rendered frame. Apply player Hard penalty after mitigation."};
  const ROWS = [
    // Tameable shore crabs attack while wild; beach seats own their population.
    {"id":"crab","name":"Crab","tier":1,"hp":10,"armor":2,"dmg":2,"range":0.6,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.3,"attackHits":1,"visionCells":4,"movement":{"pattern":"scuttle_pause","speedMetersPerSecond":1.4,"scuttleSeconds":0.7,"pauseSeconds":0.6,"approachAngleJitterRadians":0.6},"surface":null,"cave":null,"art":{"path":"assets/Farm Animals/Crab.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[0,1,2]},"up":{"idle":[3],"move":[3,4,5]},"right":{"idle":[6],"move":[6,7,8]},"left":{"idle":[9],"move":[9,10,11]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.48,"eliteEligible":false,"board":false},
    {"id":"slime","name":"Green Slime","tier":1,"hp":10,"armor":0,"dmg":1,"range":0.6,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":4,"movement":{"pattern":"ooze","speedMetersPerSecond":1.1,"chargeSpeedMetersPerSecond":1.6},"surface":{"biomes":["GRASS","WETLAND"],"minDistance":0,"maxDistance":null,"time":"any","weight":5},"cave":{"minDepth":1,"maxDepth":2,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime Green.png","frameWidth":32,"frameHeight":32},"eliteEligible":true},
    {"id":"cave_slime","name":"Cave Slime","tier":1,"hp":24,"armor":0,"dmg":6,"range":0.6,"attackType":"melee","damageIntervalSeconds":3,"windupSeconds":0.6,"attackHits":1,"visionCells":5,"movement":{"pattern":"ooze","speedMetersPerSecond":1.15},"surface":null,"cave":{"minDepth":1,"maxDepth":2,"weight":5,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime Green.png","frameWidth":32,"frameHeight":32},"eliteEligible":true},
    {"id":"bat","permanentBuffs":["flight"],"name":"Bat","tier":1,"hp":16,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":4.5,"windupSeconds":0.35,"attackHits":1,"visionCells":7,"movement":{"pattern":"orbit_swoop","source":"_wildCrowTick","orbitRadiusCells":[1.5,3.5],"maxLegCells":2.5,"flightSeconds":[0.8,1.2],"pauseSeconds":[0.6,1],"swoopEveryLegs":2,"swoopTargetRadiusCells":0.35,"easing":"quadratic_in_out","collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true,"attackCycleSeconds":4.5,"hitPolicy":"One successful contact per swoop; no contact drain while orbiting. Recovery and cooldown are included in the full attack cycle.","speedMetersPerSecond":10,"speedMeaning":"Peak instantaneous flight speed; eased leg duration must be at least 2*distance/speed."},"surface":{"biomes":["FOREST","ROCK"],"minDistance":0,"maxDistance":null,"time":"night","weight":2},"cave":{"minDepth":1,"maxDepth":2,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Bat/1Fullsheet_Bat.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":true,"artScale":0.75},
    // Hive defenders only; four authored directions, three wingbeat frames.
    {"id":"bee","permanentBuffs":["flight"],"name":"Giant Bee","tier":1,"hp":16,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":4.5,"windupSeconds":0.35,"attackHits":1,"visionCells":7,"movement":{"pattern":"orbit_swoop","source":"_wildCrowTick","orbitRadiusCells":[1.5,3.5],"maxLegCells":2.5,"flightSeconds":[0.8,1.2],"pauseSeconds":[0.6,1],"swoopEveryLegs":2,"swoopTargetRadiusCells":0.35,"easing":"quadratic_in_out","collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true,"attackCycleSeconds":4.5,"hitPolicy":"One successful contact per swoop; no contact drain while orbiting. Recovery and cooldown are included in the full attack cycle.","speedMetersPerSecond":10,"speedMeaning":"Peak instantaneous flight speed; eased leg duration must be at least 2*distance/speed."},"surface":null,"cave":null,"art":{"path":"assets/Enemy/Bee/Bee.png","frameWidth":24,"frameHeight":24,"directions":{"down":{"idle":[0,4,8,4],"move":[0,4,8,4]},"left":{"idle":[1,5,9,5],"move":[1,5,9,5]},"up":{"idle":[2,6,10,6],"move":[2,6,10,6]},"right":{"idle":[3,7,11,7],"move":[3,7,11,7]}},"bounds":[5,24],"frameMs":100},"eliteEligible":false,"artScale":0.65,"board":false},
    {"id":"purple_slime","name":"Purple Slime","tier":1,"hp":16,"armor":0,"dmg":5,"range":0.6,"attackType":"melee","damageIntervalSeconds":1.4,"windupSeconds":0.15,"attackHits":1,"visionCells":6,"movement":{"pattern":"hop_retreat","retreatDistanceFraction":0.75,"speedMetersPerSecond":2.1},"surface":null,"cave":{"minDepth":3,"maxDepth":4,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Purple Slime.png","frameWidth":32,"frameHeight":32},"eliteEligible":true,"condition":"poison"},
    {"id":"spider","name":"Spider","tier":1,"hp":13,"armor":0,"dmg":0,"range":4,"minRange":2,"attackType":"web","damageIntervalSeconds":4,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"scuttle_pause","scuttleSeconds":1.2,"pauseSeconds":0.35,"approachAngleJitterRadians":0.6,"speedMetersPerSecond":3.2},"surface":{"biomes":["FOREST","WETLAND"],"minDistance":0,"maxDistance":null,"time":"any","weight":2},"cave":{"minDepth":2,"maxDepth":3,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Spider/1Fullsheet_Spider.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":true,"artScale":0.75},
    {"id":"zombie","name":"Zombie","aura":BLIGHT_AURA,"tier":2,"hp":40,"armor":0,"dmg":10,"range":0.6,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1,"attackHits":1,"visionCells":5,"movement":{"pattern":"pursue","speedMetersPerSecond":1.2,"emergeSeconds":0.8},"surface":{"biomes":["WETLAND","RESIDENTIAL","INDUSTRIAL"],"minDistance":250,"maxDistance":null,"time":"night","weight":3},"cave":{"minDepth":2,"maxDepth":3,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Zombie/1Fullsheet_Zombie.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":true,"artScale":0.75},
    {"id":"plant","name":"Plant","tier":2,"hp":43,"armor":0,"dmg":8,"range":2,"attackType":"projectile","damageIntervalSeconds":2.5,"windupSeconds":0.5,"attackHits":1,"visionCells":6,"movement":{"pattern":"anchor_spit","preferredDistanceCells":2,"speedMetersPerSecond":0,"rooted":true},"surface":{"biomes":["GRASS","FOREST"],"minDistance":250,"maxDistance":null,"time":"any","weight":3},"cave":{"minDepth":3,"maxDepth":4,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Plant/1Fullsheet_Plant.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48","attackFrames":[24,25,26,27]},"eliteEligible":true,"artScale":0.75,"tint":"#b6b279"},
    {"id":"skeleton","name":"Skeleton","tier":2,"hp":16,"armor":2,"dmg":6,"range":0.6,"attackType":"melee","damageIntervalSeconds":1.6,"windupSeconds":0.2,"attackHits":1,"visionCells":7,"movement":{"pattern":"pursue","speedMetersPerSecond":2},"surface":{"biomes":["ROCK"],"minDistance":250,"maxDistance":null,"time":"any","weight":2},"cave":{"minDepth":3,"maxDepth":4,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Skeleton/1Fullsheet_Skeleton.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":true,"artScale":0.75},
    {"id":"goblin","name":"Goblin","tier":3,"hp":48,"armor":0,"dmg":9,"range":0.6,"attackType":"melee","damageIntervalSeconds":1.8,"windupSeconds":0.25,"attackHits":1,"visionCells":9,"movement":{"pattern":"pursue_retreat","retreatDistanceFraction":0.5,"speedMetersPerSecond":7},"surface":{"biomes":["COMMERCIAL"],"minDistance":750,"maxDistance":null,"time":"any","weight":3},"cave":{"minDepth":3,"maxDepth":4,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Goblin.png","frameWidth":32,"frameHeight":32,"directionLayout":"goblin18"},"eliteEligible":true},
    {"id":"goblin_archer","name":"Goblin Archer","tier":3,"hp":57,"armor":0,"dmg":10,"range":3,"attackType":"projectile","damageIntervalSeconds":3.5,"windupSeconds":0.7,"attackHits":1,"visionCells":10,"movement":{"pattern":"keep_distance","preferredDistanceCells":3,"speedMetersPerSecond":5.6},"surface":{"biomes":["COMMERCIAL"],"minDistance":750,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":4,"maxDepth":5,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Goblin Archer.png","frameWidth":32,"frameHeight":32,"directionLayout":"goblin18"},"eliteEligible":true},
    {"id":"goblin_trapper","name":"Goblin Trapper","tier":3,"hp":40,"armor":0,"dmg":0,"range":3,"attackType":"trap","damageIntervalSeconds":10,"windupSeconds":0.6,"attackHits":1,"visionCells":9,"movement":{"pattern":"keep_distance","preferredDistanceCells":3,"retreatDistanceFraction":0.5,"speedMetersPerSecond":5.4},"surface":null,"cave":{"minDepth":5,"maxDepth":6,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Goblin.png","frameWidth":32,"frameHeight":32,"directionLayout":"goblin18","tint":"#ff4a3a"},"tint":"#ff4a3a","eliteEligible":false},
    {"id":"vampire_bat","permanentBuffs":["flight"],"name":"Vampire Bat","tier":3,"hp":39,"armor":0,"dmg":14,"range":1,"attackType":"melee","damageIntervalSeconds":3.6,"windupSeconds":0.3,"attackHits":1,"visionCells":8,"movement":{"pattern":"orbit_swoop","source":"_wildCrowTick","orbitRadiusCells":[1.25,3],"maxLegCells":2.5,"flightSeconds":[0.65,0.95],"pauseSeconds":[0.4,0.7],"swoopEveryLegs":2,"swoopTargetRadiusCells":0.35,"easing":"quadratic_in_out","collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true,"attackCycleSeconds":3.6,"hitPolicy":"One successful contact per swoop; no contact drain while orbiting. Recovery and cooldown are included in the full attack cycle.","speedMetersPerSecond":10,"speedMeaning":"Peak instantaneous flight speed; eased leg duration must be at least 2*distance/speed."},"surface":null,"cave":{"minDepth":4,"maxDepth":5,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Bat/Reskin/1Fullsheet_VampireBat.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"palette":{"shadow":"#164e61","mid":"#34e7ee","highlight":"#ecffff","gamma":0.4},"eliteEligible":true,"artScale":0.75},
    {"id":"brute","name":"Brute","tier":4,"hp":95,"armor":0,"dmg":16,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1.1,"attackHits":1,"visionCells":5,"movement":{"pattern":"lumber","speedMetersPerSecond":1.3},"surface":null,"cave":{"minDepth":5,"maxDepth":6,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Brute/1Fullsheet_Brute.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":false,"artScale":0.75},
    {"id":"poison_spider","name":"Poison Spider","tier":4,"hp":61,"armor":0,"dmg":0,"range":4,"minRange":2,"attackType":"web","damageIntervalSeconds":4,"windupSeconds":0.6,"attackHits":1,"visionCells":7,"movement":{"pattern":"scuttle_pause","scuttleSeconds":1.4,"pauseSeconds":0.25,"approachAngleJitterRadians":0.8,"speedMetersPerSecond":3.8},"surface":null,"cave":{"minDepth":5,"maxDepth":6,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Spider/Reskin/1Fullsheet_PoisonSpider.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":true,"artScale":0.75},
    {"id":"dryad","name":"Dryad","tier":4,"hp":61,"armor":0,"dmg":14,"range":3,"attackType":"projectile","damageIntervalSeconds":3,"windupSeconds":0.7,"attackHits":1,"visionCells":8,"movement":{"pattern":"strafe_cast","preferredDistanceCells":3,"strafeAngleRadians":0.6,"speedMetersPerSecond":2.2},"surface":null,"cave":{"minDepth":6,"maxDepth":7,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Succubus/Reskin/1Fullsheet_Dryad.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":true,"artScale":0.75},
    {"id":"lich","name":"Lich","tier":5,"hp":52,"armor":6,"dmg":16,"range":3,"attackType":"projectile","damageIntervalSeconds":4,"windupSeconds":0.8,"attackHits":1,"visionCells":8,"movement":{"pattern":"strafe_cast","preferredDistanceCells":3,"speedMetersPerSecond":1.8},"surface":null,"cave":{"minDepth":8,"maxDepth":null,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Skeleton/Reskin/1Fullsheet_DrySkeleton.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"palette":{"shadow":"#102b18","mid":"#71dc34","highlight":"#e6ffc0"},"aura":{...BLIGHT_AURA,"radiusCells":1.5},"projectile":"blight_magic","eliteEligible":true,"artScale":0.75},
    {"id":"bone_plant","name":"Bone Plant","tier":5,"hp":77,"armor":4,"dmg":18,"range":3,"attackType":"projectile","damageIntervalSeconds":4,"windupSeconds":0.8,"attackHits":1,"visionCells":8,"movement":{"pattern":"anchor_spit","preferredDistanceCells":3,"speedMetersPerSecond":0,"rooted":true},"surface":null,"cave":{"minDepth":7,"maxDepth":8,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Plant/Reskin/1Fullsheet_BonePlant.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":true,"artScale":0.75},
    {"id":"fiend","name":"Fiend","tier":5,"hp":73,"armor":0,"dmg":13,"range":0.6,"attackType":"melee","damageIntervalSeconds":1.25,"windupSeconds":0.15,"attackHits":1,"visionCells":8,"movement":{"pattern":"lunge_recover","lungeSeconds":0.6,"lungeWindupSeconds":0.5,"lungeCooldownSeconds":4,"speedMetersPerSecond":3.5,"lungeSpeedMetersPerSecond":5.5},"surface":null,"cave":{"minDepth":5,"maxDepth":6,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Zombie/Reskin/1Fullsheet_Fiend.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":true,"artScale":0.75,"lavaImmune":true},
    {"id":"succubus","name":"Succubus","tier":6,"hp":137,"armor":2,"dmg":18,"range":4,"attackType":"projectile","damageIntervalSeconds":3,"windupSeconds":0.6,"attackHits":1,"visionCells":10,"movement":{"pattern":"strafe_cast","preferredDistanceCells":4,"strafeAngleRadians":0.9,"speedMetersPerSecond":2.6},"surface":null,"cave":{"minDepth":7,"maxDepth":8,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Succubus/1Fullsheet_Succubus.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":true,"artScale":0.75,"lavaImmune":true},
    {"id":"hell_brute","name":"Hell Brute","tier":7,"hp":225,"armor":0,"dmg":28,"range":1,"attackType":"melee","damageIntervalSeconds":5,"windupSeconds":1.5,"attackHits":1,"visionCells":6,"movement":{"pattern":"lumber","speedMetersPerSecond":1.1},"surface":null,"cave":{"minDepth":9,"maxDepth":null,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Brute/Reskin/1Fullsheet_HellBrute.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":false,"artScale":0.75,"lavaImmune":true},
    {"id":"ghost","permanentBuffs":["flight"],"name":"Ghost","tier":3,"hp":20,"armor":0,"dmg":12,"range":1,"attackType":"touch","damageIntervalSeconds":null,"windupSeconds":0,"attackHits":1,"visionCells":6,"movement":{"pattern":"ghost_glide","speedMetersPerSecond":3,"collision":"existing_ghost_rules"},"surface":{"biomes":["GRASS","FOREST","ROCK","SAND","RESIDENTIAL","COMMERCIAL","INDUSTRIAL","WETLAND","ORCHARD"],"minDistance":750,"maxDistance":null,"time":"night","weight":1},"cave":{"minDepth":2,"maxDepth":null,"weight":2,"depthRule":"even"},"art":{"path":"assets/Enemy/Ghost/1Fullsheet_Ghost.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":false,"artScale":0.75},
    {"id":"pink_ghost","permanentBuffs":["flight"],"name":"Pink Ghost","tier":5,"hp":30,"armor":0,"dmg":16,"range":1,"attackType":"touch","damageIntervalSeconds":null,"windupSeconds":0,"attackHits":1,"visionCells":8,"movement":{"pattern":"ghost_glide","speedMetersPerSecond":3.5,"collision":"existing_ghost_rules"},"surface":null,"cave":{"minDepth":6,"maxDepth":null,"weight":1,"depthRule":"even"},"art":{"path":"assets/Enemy/Ghost/Reskin/1Fullsheet_PinkGhost.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"eliteEligible":false,"artScale":0.75},
    {"id":"mini_slime","name":"Mini Green Slime","tier":1,"hp":5,"armor":0,"dmg":1,"range":0.6,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":4,"movement":{"pattern":"ooze","speedMetersPerSecond":1.23},"surface":{"biomes":["GRASS"],"minDistance":0,"maxDistance":null,"time":"any","weight":2},"cave":{"minDepth":1,"maxDepth":2,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime Green.png","frameWidth":32,"frameHeight":32},"variantOf":"slime","variantType":"Mini","eliteEligible":false,"board":false,"retired":true},
    {"id":"mini_spider","name":"Mini Spider","tier":1,"hp":11,"armor":0,"dmg":0,"range":4,"minRange":2,"attackType":"web","damageIntervalSeconds":4,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"scuttle_pause","scuttleSeconds":1.2,"pauseSeconds":0.35,"approachAngleJitterRadians":0.6,"speedMetersPerSecond":3.58},"surface":{"biomes":["FOREST","ORCHARD"],"minDistance":0,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":1,"maxDepth":3,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Spider/1Fullsheet_Spider.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"variantOf":"spider","variantType":"Mini","eliteEligible":false,"artScale":1.333333333333333,"board":false,"retired":true},
    {"id":"giant_slime","name":"Giant Green Slime","tier":2,"hp":31,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":3.6,"windupSeconds":0.7,"attackHits":1,"visionCells":4,"movement":{"pattern":"ooze","speedMetersPerSecond":1.1},"surface":{"biomes":["WETLAND"],"minDistance":250,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":3,"maxDepth":5,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime Green.png","frameWidth":32,"frameHeight":32},"variantOf":"slime","variantType":"Giant","artScale":0.8,"eliteEligible":false,"board":false,"retired":true},
    {"id":"giant_spider","name":"Giant Spider","tier":3,"hp":39,"armor":0,"dmg":0,"range":4,"minRange":2,"attackType":"web","damageIntervalSeconds":4,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"scuttle_pause","scuttleSeconds":1.2,"pauseSeconds":0.35,"approachAngleJitterRadians":0.6,"speedMetersPerSecond":2.72},"surface":{"biomes":["FOREST","ORCHARD","WETLAND"],"minDistance":750,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":4,"maxDepth":6,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Spider/1Fullsheet_Spider.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"variantOf":"spider","variantType":"Giant","eliteEligible":false,"artScale":1.333333333333333,"board":false,"retired":true},
    {"id":"giant_skeleton","name":"Giant Skeleton","tier":3,"hp":37,"armor":2,"dmg":12,"range":1,"attackType":"melee","damageIntervalSeconds":2.6,"windupSeconds":0.5,"attackHits":1,"visionCells":7,"movement":{"pattern":"pursue","speedMetersPerSecond":1.7},"surface":{"biomes":["ROCK","SAND","INDUSTRIAL"],"minDistance":1500,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":5,"maxDepth":8,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Skeleton/1Fullsheet_Skeleton.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"variantOf":"skeleton","variantType":"Giant","artScale":0.7,"tint":"#f0c878","eliteEligible":false,"board":false,"retired":true},
    {"id":"giant_cave_slime","name":"Giant Cave Slime","tier":3,"hp":66,"armor":0,"dmg":12,"range":1,"attackType":"melee","damageIntervalSeconds":3.6,"windupSeconds":0.7,"attackHits":1,"visionCells":5,"movement":{"pattern":"ooze","speedMetersPerSecond":1.1},"surface":null,"cave":{"minDepth":3,"maxDepth":5,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime Green.png","frameWidth":32,"frameHeight":32},"variantOf":"cave_slime","variantType":"Giant","artScale":0.75,"eliteEligible":false,"board":false,"retired":true},
    {"id":"giant_lich","name":"Giant Lich","tier":7,"hp":110,"armor":6,"dmg":24,"range":4,"attackType":"projectile","damageIntervalSeconds":5,"windupSeconds":1,"attackHits":1,"visionCells":9,"movement":{"pattern":"strafe_cast","preferredDistanceCells":4,"speedMetersPerSecond":1.53},"surface":null,"cave":{"minDepth":8,"maxDepth":null,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Skeleton/Reskin/1Fullsheet_DrySkeleton.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"palette":{"shadow":"#102b18","mid":"#71dc34","highlight":"#e6ffc0"},"aura":{...BLIGHT_AURA,"radiusCells":2.4},"projectile":"blight_magic","variantOf":"lich","variantType":"Giant","eliteEligible":false,"board":false,"retired":true},
    {"id":"moss_slime","name":"Moss Green Slime","tier":1,"hp":10,"armor":0,"dmg":1,"range":0.6,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":4,"movement":{"pattern":"ooze","speedMetersPerSecond":1.1},"surface":{"biomes":["FOREST","ORCHARD"],"minDistance":0,"maxDistance":null,"time":"any","weight":2},"cave":null,"art":{"path":"assets/Enemy/Slime Green.png","frameWidth":32,"frameHeight":32,"tint":"#8ea660"},"tint":"#8ea660","variantOf":"slime","variantType":"Tint","eliteEligible":true,"board":false,"retired":true},
    // The tar yard's FIRE SLIME (lairs.js KIND_ORDER tar / burned): zone-seated only,
    // never a surface or cave draw; off the quest board; its kill drops a flint
    // (sprite_layout.js CREATURE_BEHAVIOUR.fire_slime). The slime's ooze and
    // charge; a bite every two seconds.
    {"id":"fire_slime","name":"Fire Slime","tier":2,"hp":20,"armor":0,"dmg":4,"range":0.6,"attackType":"melee","damageIntervalSeconds":2,"windupSeconds":0.3,"attackHits":1,"visionCells":4,"movement":{"pattern":"ooze","speedMetersPerSecond":1.1,"chargeSpeedMetersPerSecond":1.6},"surface":null,"cave":null,"art":{"path":"assets/Enemy/Slime Green.png","frameWidth":32,"frameHeight":32,"tint":"#ff5a28"},"tint":"#ff5a28","variantOf":"slime","variantType":"Tint","eliteEligible":true,"board":false},
    {"id":"sand_skeleton","name":"Sand Skeleton","tier":2,"hp":16,"armor":2,"dmg":6,"range":0.6,"attackType":"melee","damageIntervalSeconds":1.6,"windupSeconds":0.2,"attackHits":1,"visionCells":7,"movement":{"pattern":"pursue","speedMetersPerSecond":2},"surface":{"biomes":["SAND"],"minDistance":250,"maxDistance":null,"time":"any","weight":2},"cave":null,"art":{"path":"assets/Enemy/Skeleton/1Fullsheet_Skeleton.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48","tint":"#d4b276"},"tint":"#d4b276","variantOf":"skeleton","variantType":"Tint","eliteEligible":true,"board":false,"retired":true},
    {"id":"marsh_zombie","name":"Marsh Zombie","tier":2,"hp":40,"armor":0,"dmg":10,"range":0.6,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1,"attackHits":1,"visionCells":5,"movement":{"pattern":"pursue","speedMetersPerSecond":1.2},"surface":{"biomes":["INDUSTRIAL"],"minDistance":250,"maxDistance":null,"time":"night","weight":2,"replaceBase":false},"cave":null,"art":{"path":"assets/Enemy/Zombie/1Fullsheet_Zombie.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48","tint":"#819d78"},"tint":"#819d78","variantOf":"zombie","variantType":"Tint","eliteEligible":true,"board":false},
    {"id":"copper_plant","name":"Copper Plant","tier":2,"hp":43,"armor":0,"dmg":8,"range":2,"attackType":"projectile","damageIntervalSeconds":2.5,"windupSeconds":0.5,"attackHits":1,"visionCells":6,"movement":{"pattern":"anchor_spit","preferredDistanceCells":2,"speedMetersPerSecond":0,"rooted":true},"surface":{"biomes":["ORCHARD"],"minDistance":250,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/Plant/1Fullsheet_Plant.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48","tint":"#c68f60","attackFrames":[24,25,26,27]},"palette":{"shadow":"#351108","mid":"#e66b13","highlight":"#ffe6a6"},"variantOf":"plant","variantType":"Tint","eliteEligible":true,"board":false,"retired":true},
    {"id":"ash_zombie","name":"Ash Zombie","tier":2,"hp":40,"armor":0,"dmg":10,"range":0.6,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1,"attackHits":1,"visionCells":5,"movement":{"pattern":"pursue","speedMetersPerSecond":1.2},"surface":{"biomes":["INDUSTRIAL"],"minDistance":250,"maxDistance":null,"time":"night","weight":1,"replaceBase":false},"cave":null,"art":{"path":"assets/Enemy/Zombie/1Fullsheet_Zombie.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"tint":"#9aa3b2","variantOf":"zombie","variantType":"Tint","eliteEligible":true,"board":false},
    {"id":"obsidian_brute","name":"Obsidian Brute","tier":4,"hp":95,"armor":0,"dmg":16,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1.1,"attackHits":1,"visionCells":5,"movement":{"pattern":"lumber","speedMetersPerSecond":1.3},"surface":null,"cave":{"minDepth":6,"maxDepth":9,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Brute/1Fullsheet_Brute.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48"},"tint":"#8386a8","variantOf":"brute","variantType":"Tint","eliteEligible":false,"board":false,"retired":true},
    {"id":"giant_plant","name":"Giant Plant","tier":3,"hp":57,"armor":0,"dmg":14,"range":3,"attackType":"projectile","damageIntervalSeconds":5,"windupSeconds":1,"attackHits":1,"visionCells":7,"movement":{"pattern":"anchor_spit","preferredDistanceCells":3,"speedMetersPerSecond":0,"rooted":true},"surface":null,"cave":{"minDepth":4,"maxDepth":7,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Plant/1Fullsheet_Plant.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48","attackFrames":[24,25,26,27]},"variantOf":"plant","variantType":"Giant","eliteEligible":false,"artScale":1.333333333333333,"board":false,"retired":true},
    {"id":"gull","permanentBuffs":["flight"],"name":"Gull","tier":1,"hp":8,"armor":0,"dmg":0,"steals":"food","range":1,"attackType":"melee","damageIntervalSeconds":6,"windupSeconds":0.3,"attackHits":1,"visionCells":6,"movement":{"pattern":"orbit_swoop","source":"_wildCrowTick","orbitRadiusCells":[1.5,3.5],"maxLegCells":2.5,"flightSeconds":[0.8,1.2],"pauseSeconds":[0.6,1],"swoopEveryLegs":2,"swoopTargetRadiusCells":0.35,"easing":"quadratic_in_out","collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true,"attackCycleSeconds":6,"hitPolicy":"One successful snatch per swoop \u2014 one piece of food out of the bag; a gull that has stolen today is sated and flies off.","speedMetersPerSecond":5,"speedMeaning":"Peak instantaneous flight speed; eased leg duration must be at least 2*distance/speed."},"surface":null,"cave":null,"board":false,"art":{"path":"assets/Objects/Wilderness/Crow.png","frameWidth":32,"frameHeight":32},"palette":{"shadow":"#7d8a96","mid":"#e4ebf0","highlight":"#ffffff","gamma":0.3},"eliteEligible":false},
    {"id":"raven","permanentBuffs":["flight"],"name":"Raven","tier":1,"hp":10,"armor":0,"dmg":0,"steals":"coins","range":1,"attackType":"melee","damageIntervalSeconds":6,"windupSeconds":0.3,"attackHits":1,"visionCells":6,"movement":{"pattern":"orbit_swoop","source":"_wildCrowTick","orbitRadiusCells":[1.5,3.5],"maxLegCells":2.5,"flightSeconds":[0.8,1.2],"pauseSeconds":[0.6,1],"swoopEveryLegs":2,"swoopTargetRadiusCells":0.35,"easing":"quadratic_in_out","collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true,"attackCycleSeconds":6,"hitPolicy":"One successful snatch per swoop \u2014 a single coin out of the purse; a raven that has stolen today is sated and flies off.","speedMetersPerSecond":5,"speedMeaning":"Peak instantaneous flight speed; eased leg duration must be at least 2*distance/speed."},"surface":null,"cave":null,"board":false,"art":{"path":"assets/Objects/Wilderness/Crow.png","frameWidth":32,"frameHeight":32},"palette":{"shadow":"#141230","mid":"#2f2a6b","highlight":"#8f7fe0","gamma":0.3},"eliteEligible":false},
    {"id":"pirate_grunt","name":"Pirate Grunt","pirate":true,"tier":2,"hp":30,"armor":0,"dmg":7,"range":0.6,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":2},"surface":{"biomes":[],"minDistance":250,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/Pirates/PirateGrunt.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22,23,24]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27,28,29]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32,33,34]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37,38,39]}},"directionSideFacing":"right","bounds":[3,15],"frameMs":180},"artScale":0.75,"eliteEligible":true},
    {"id":"thief","name":"Thief","tier":2,"hp":30,"armor":0,"dmg":15,"range":0.6,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":3},"surface":{"biomes":["RESIDENTIAL"],"minDistance":250,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/Pirates/PirateGrunt.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22,23,24]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27,28,29]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32,33,34]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37,38,39]}},"directionSideFacing":"right","bounds":[3,15],"frameMs":180},"artScale":0.75,"eliteEligible":false,"palette":{"shadow":"#21162d","mid":"#76528d","highlight":"#d3bcd9","gamma":0.85},"hitAndRun":{"coins":15}},
    {"id":"pirate_gunner","name":"Pirate Gunner","pirate":true,"tier":3,"hp":34,"armor":0,"dmg":10,"range":3,"attackType":"projectile","damageIntervalSeconds":4,"windupSeconds":1,"attackHits":1,"visionCells":6,"movement":{"pattern":"keep_distance","speedMetersPerSecond":1.8,"preferredDistanceCells":3,"stopToReload":true,"reloadSeconds":1.2},"surface":null,"cave":null,"art":{"path":"assets/Enemy/Pirates/PirateGunner.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22,23]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27,28]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32,33]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37,38]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true,"projectile":"bullet"},
    {"id":"pirate_captain","name":"Pirate Captain","pirate":true,"tier":3,"hp":65,"armor":2,"dmg":12,"range":0.6,"attackType":"melee","damageIntervalSeconds":3,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":2},"surface":null,"cave":null,"art":{"path":"assets/Enemy/Pirates/PirateCaptain.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22,23]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27,28]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32,33]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37,38]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true},
    {"id":"giant_crab","name":"Giant Crab","tier":1,"hp":22,"armor":0,"dmg":5,"range":1,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"scuttle_pause","speedMetersPerSecond":1.4,"scuttleSeconds":0.7,"pauseSeconds":0.6,"approachAngleJitterRadians":1.2,"territoryCells":3},"surface":{"biomes":["SAND","WETLAND"],"minDistance":0,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/GiantCrab.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2]},"up":{"idle":[3],"move":[4,5]},"left":{"idle":[6],"move":[7,8]},"right":{"idle":[9],"move":[10,11]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true},
    {"id":"farmer_goblin","name":"Farmer Goblin","tier":2,"hp":27,"armor":0,"dmg":6,"range":0.6,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue_retreat","speedMetersPerSecond":4.4,"retreatDistanceFraction":0.5},"surface":{"biomes":["FARMLAND","ORCHARD"],"minDistance":250,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/Orcs/FarmerGoblin.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[15,16,17]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[20,21,22]},"side":{"idle":[10],"move":[11,12,13,14],"attack":[25,26,27]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true},
    {"id":"club_goblin","name":"Club Goblin","tier":2,"hp":30,"armor":0,"dmg":7,"range":0.6,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":5},"surface":{"biomes":["COMMERCIAL"],"minDistance":250,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":1,"maxDepth":2,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Orcs/ClubGoblin.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true},
    {"id":"spear_goblin","name":"Spear Goblin","tier":3,"hp":40,"armor":0,"dmg":9,"range":2,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"keep_distance","speedMetersPerSecond":3.6,"preferredDistanceCells":2},"surface":null,"cave":{"minDepth":2,"maxDepth":3,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Orcs/SpearGoblin.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4]},"up":{"idle":[5],"move":[6,7,8,9]},"left":{"idle":[10],"move":[11,12,13,14]},"right":{"idle":[15],"move":[16,17,18,19]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true},
    {"id":"archer_goblin","name":"Archer Goblin","tier":3,"hp":30,"armor":0,"dmg":8,"range":3,"attackType":"projectile","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"keep_distance","speedMetersPerSecond":4,"preferredDistanceCells":3},"surface":null,"cave":{"minDepth":3,"maxDepth":4,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Orcs/ArcherGoblin.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true,"projectile":"arrow"},
    {"id":"bomb_goblin","name":"Bomb Goblin","tier":3,"hp":20,"armor":0,"dmg":14,"range":1,"attackType":"blast","damageIntervalSeconds":4,"windupSeconds":1.5,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":5.2},"surface":null,"cave":{"minDepth":4,"maxDepth":5,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Orcs/KamikazeGoblin.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22,23,24]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27,28,29]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32,33,34]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37,38,39]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true,"blast":{"radiusCells":1.5}},
    {"id":"orc","name":"Orc","tier":3,"hp":65,"armor":3,"dmg":12,"range":1,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"lumber","speedMetersPerSecond":3},"surface":null,"cave":{"minDepth":4,"maxDepth":5,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Orcs/Orc.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[24,25,26,27,28,29]},"up":{"idle":[6],"move":[7,8,9,10],"attack":[30,31,32,33,34,35]},"left":{"idle":[12],"move":[13,14,15,16],"attack":[36,37,38,39,40,41]},"right":{"idle":[18],"move":[19,20,21,22],"attack":[42,43,44,45,46,47]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true},
    {"id":"orc_mage","name":"Orc Mage","tier":3,"hp":48,"armor":0,"dmg":12,"range":3,"attackType":"projectile","damageIntervalSeconds":3.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"strafe_cast","speedMetersPerSecond":3,"preferredDistanceCells":3},"surface":null,"cave":{"minDepth":6,"maxDepth":7,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Orcs/OrcMage.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[24,25,26,27,28,29]},"up":{"idle":[6],"move":[7,8,9,10],"attack":[30,31,32,33,34,35]},"left":{"idle":[12],"move":[13,14,15,16],"attack":[36,37,38,39,40,41]},"right":{"idle":[18],"move":[19,20,21,22],"attack":[42,43,44,45,46,47]}},"directionSideFacing":"right","bounds":[2,15],"frameMs":180},"artScale":0.75,"eliteEligible":true},
    {"id":"orc_shaman","name":"Orc Shaman","tier":3,"hp":52,"armor":0,"dmg":7,"range":3,"attackType":"projectile","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"keep_distance","speedMetersPerSecond":3,"preferredDistanceCells":3},"surface":null,"cave":{"minDepth":7,"maxDepth":8,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Orcs/OrcShaman.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22,23,24]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27,28,29]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32,33,34]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37,38,39]}},"directionSideFacing":"right","bounds":[2,15],"frameMs":180},"artScale":0.75,"eliteEligible":true,"ability":{"type":"heal","radiusCells":3,"amount":2,"intervalSeconds":8,"windupSeconds":1.2}},
    {"id":"minotaur","name":"Minotaur","tier":4,"hp":95,"armor":0,"dmg":18,"range":1,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":6,"movement":{"pattern":"lunge_recover","speedMetersPerSecond":1.5,"lungeSeconds":1.2,"lungeWindupSeconds":0.7,"lungeCooldownSeconds":5,"lungeSpeedMetersPerSecond":5,"chargeOnly":true},"surface":null,"cave":{"minDepth":8,"maxDepth":null,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[366,367,368],"move":[366,367,368]},"left":{"idle":[396,397,398],"move":[396,397,398]},"right":{"idle":[426,427,428],"move":[426,427,428]},"up":{"idle":[456,457,458],"move":[456,457,458]}},"directionSideFacing":"right","bounds":[0,16],"frameMs":180},"artScale":1,"eliteEligible":true},
    {"id":"necromancer","name":"Necromancer","tier":5,"hp":70,"armor":0,"dmg":12,"range":3,"attackType":"projectile","damageIntervalSeconds":4,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"strafe_cast","speedMetersPerSecond":1.5,"preferredDistanceCells":3},"surface":null,"cave":{"minDepth":6,"maxDepth":7,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Necromancer.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[24,25,26,27,28,29]},"up":{"idle":[6],"move":[7,8,9,10],"attack":[30,31,32,33,34,35]},"left":{"idle":[12],"move":[13,14,15,16],"attack":[36,37,38,39,40,41]},"right":{"idle":[18],"move":[19,20,21,22],"attack":[42,43,44,45,46,47]}},"directionSideFacing":"right","bounds":[1,14],"frameMs":180},"artScale":0.75,"eliteEligible":true,"ability":{"type":"summon","kind":"skeleton","maxMinions":2,"intervalSeconds":12,"windupSeconds":1.2}},
    {"id":"skeleton_soldier","name":"Skeleton Soldier","tier":3,"hp":38,"armor":4,"dmg":10,"range":0.6,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":1.7},"surface":{"biomes":["ROCK"],"minDistance":750,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":5,"maxDepth":6,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Skeleton/Skeleton-Soldier.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22,23]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27,28]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32,33]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37,38]}},"directionSideFacing":"right","bounds":[2,14],"frameMs":180},"artScale":0.75,"eliteEligible":true},
    {"id":"red_demon","storyReward":"fire_breath","name":"Red Demon","tier":5,"hp":75,"armor":0,"dmg":15,"range":1,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"lunge_recover","speedMetersPerSecond":2,"lungeSeconds":0.6,"lungeWindupSeconds":0.8,"lungeCooldownSeconds":4,"lungeSpeedMetersPerSecond":4.5},"surface":null,"cave":{"minDepth":8,"maxDepth":9,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Demons/RedDemon.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[24,25,26,27,28,29]},"up":{"idle":[6],"move":[7,8,9,10],"attack":[30,31,32,33,34,35]},"left":{"idle":[12],"move":[13,14,15,16],"attack":[36,37,38,39,40,41]},"right":{"idle":[18],"move":[19,20,21,22],"attack":[42,43,44,45,46,47]}},"directionSideFacing":"right","bounds":[2,16],"frameMs":180},"artScale":0.75,"eliteEligible":true,"lavaImmune":true},
    {"id":"purple_demon","storyReward":"fire_breath","name":"Purple Demon","tier":5,"hp":65,"armor":0,"dmg":14,"range":3,"attackType":"area","damageIntervalSeconds":4,"windupSeconds":1.2,"attackHits":1,"visionCells":6,"movement":{"pattern":"strafe_cast","speedMetersPerSecond":1.7,"preferredDistanceCells":3},"surface":null,"cave":{"minDepth":8,"maxDepth":9,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Demons/PurpleDemon.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[24,25,26,27,28,29]},"up":{"idle":[6],"move":[7,8,9,10],"attack":[30,31,32,33,34,35]},"left":{"idle":[12],"move":[13,14,15,16],"attack":[36,37,38,39,40,41]},"right":{"idle":[18],"move":[19,20,21,22],"attack":[42,43,44,45,46,47]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true,"area":{"radiusCells":1},"lavaImmune":true},
    {"id":"armoured_demon","storyReward":"fire_breath","name":"Armoured Demon","tier":6,"hp":130,"armor":7,"dmg":22,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1.3,"attackHits":1,"visionCells":6,"movement":{"pattern":"lumber","speedMetersPerSecond":1.2},"surface":null,"cave":{"minDepth":9,"maxDepth":null,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Demons/ArmouredRedDemon.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[24,25,26,27,28,29]},"up":{"idle":[6],"move":[7,8,9,10],"attack":[30,31,32,33,34,35]},"left":{"idle":[12],"move":[13,14,15,16],"attack":[36,37,38,39,40,41]},"right":{"idle":[18],"move":[19,20,21,22],"attack":[42,43,44,45,46,47]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"artScale":0.75,"eliteEligible":true,"lavaImmune":true},
    {"id":"red_dragon","name":"Red Dragon","tier":7,"hp":210,"armor":4,"dmg":25,"range":4,"attackType":"breath","damageIntervalSeconds":5,"windupSeconds":1.5,"attackHits":1,"visionCells":6,"movement":{"pattern":"keep_distance","speedMetersPerSecond":1.2,"preferredDistanceCells":3,"territoryCells":5},"surface":null,"cave":{"minDepth":9,"maxDepth":null,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Dragons/RedDragon.png","frameWidth":32,"frameHeight":32,"directions":{"down":{"idle":[0],"move":[1,2,3],"attack":[16,17]},"up":{"idle":[4],"move":[5,6,7],"attack":[20,21]},"left":{"idle":[8],"move":[9,10,11],"attack":[24,25]},"right":{"idle":[12],"move":[13,14,15],"attack":[28,29]}},"directionSideFacing":"right","bounds":[2,28],"frameMs":180},"artScale":0.65,"eliteEligible":false,"breath":{"halfAngleRadians":0.4},"lavaImmune":true},
    {"id":"metal_slime","name":"Metal Slime","tier":3,"hp":375,"armor":0,"dmg":0,"range":1,"attackType":"none","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":6,"movement":{"pattern":"flee","speedMetersPerSecond":2.4},"surface":null,"cave":null,"board":false,"bountyCoins":75,"art":{"path":"assets/Enemy/Slime/1Fullsheet_Slime.png","frameWidth":16,"frameHeight":16,"directionLayout":"enemy48","bounds":[5,16]},"artScale":0.625,"palette":{"shadow":"#424a58","mid":"#aeb9c7","highlight":"#ffffff"},"eliteEligible":false},
    {"id":"boar","name":"Boar","tier":1,"hp":14,"armor":0,"dmg":4,"range":0.6,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":6,"movement":{"pattern":"lunge_recover","chargeOnly":true,"speedMetersPerSecond":1.2,"lungeSeconds":1.6,"lungeWindupSeconds":0.7,"lungeCooldownSeconds":5,"lungeSpeedMetersPerSecond":6.5,"hitPolicy":"Charges in a straight line, then stands to catch its breath; it only hurts what it runs into during a charge."},"surface":{"biomes":["FOREST"],"minDistance":150,"maxDistance":null,"time":"any","weight":2},"cave":null,"art":{"path":"assets/Enemy/Boar.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[0,1,2,3],"attack":[16,17,18]},"up":{"idle":[4],"move":[4,5,6,7],"attack":[20,21,22]},"right":{"idle":[8],"move":[8,9,10,11],"attack":[24,25,26]},"left":{"idle":[12],"move":[12,13,14,15],"attack":[28,29,30]}},"directionSideFacing":"right","bounds":[2,14],"frameMs":160},"artScale":0.85,"eliteEligible":true},
    // ── GUARD-GROUP KINDS (lairs.js GROUPS, Oct 2026) — seated only by an authored
    // garrison, never by the surface or cave bags (no `surface`, no `cave`):
    //   the RUNT is a club goblin's Mini (the horde: fifteen weak ones);
    //   the SPLITTING SLIME divides when struck (creature_ai.js enemySplit — its
    //     `ability`: half its health on each side, a cell away, while a half
    //     still has minHp twice over), a Tint variant of the surface slime drawn
    //     ice-blue; it never rolls elite and pays its bounty by share;
    //   the STORM GULL is the shore gull's sheet gone grey and turned hostile
    //     (a peck, not a theft), the bat's orbit-and-swoop flight.
    {"id":"goblin_runt","name":"Goblin Runt","tier":1,"hp":10,"armor":0,"dmg":3,"range":0.6,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":5},"surface":null,"cave":null,"board":false,"art":{"path":"assets/Enemy/Orcs/ClubGoblin.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0],"move":[1,2,3,4],"attack":[20,21,22]},"up":{"idle":[5],"move":[6,7,8,9],"attack":[25,26,27]},"left":{"idle":[10],"move":[11,12,13,14],"attack":[30,31,32]},"right":{"idle":[15],"move":[16,17,18,19],"attack":[35,36,37]}},"directionSideFacing":"right","bounds":[1,15],"frameMs":180},"variantOf":"club_goblin","variantType":"Mini","eliteEligible":false},
    {"id":"split_slime","name":"Splitting Slime","tier":1,"hp":32,"armor":0,"dmg":2,"range":0.6,"attackType":"melee","damageIntervalSeconds":1.2,"windupSeconds":0.1,"attackHits":1,"visionCells":5,"movement":{"pattern":"ooze","speedMetersPerSecond":1.3,"chargeSpeedMetersPerSecond":1.6},"surface":null,"cave":null,"board":false,"art":{"path":"assets/Enemy/Slime Green.png","frameWidth":32,"frameHeight":32},"palette":{"shadow":"#1b3f66","mid":"#46a6dc","highlight":"#e2f7ff","gamma":0.9},"variantOf":"slime","variantType":"Tint","eliteEligible":false,"ability":{"type":"split","minHp":4,"cooldownSeconds":1.5}},
    {"id":"storm_gull","permanentBuffs":["flight"],"name":"Storm Gull","tier":1,"hp":8,"armor":0,"dmg":3,"range":1,"attackType":"melee","damageIntervalSeconds":4.5,"windupSeconds":0.3,"attackHits":1,"visionCells":7,"movement":{"pattern":"orbit_swoop","source":"_wildCrowTick","orbitRadiusCells":[1.5,3.5],"maxLegCells":2.5,"flightSeconds":[0.8,1.2],"pauseSeconds":[0.5,0.9],"swoopEveryLegs":2,"swoopTargetRadiusCells":0.35,"easing":"quadratic_in_out","collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true,"attackCycleSeconds":4.5,"hitPolicy":"One peck per swoop; no contact drain while orbiting. Recovery and cooldown are included in the full attack cycle.","speedMetersPerSecond":5,"speedMeaning":"Peak instantaneous flight speed; eased leg duration must be at least 2*distance/speed."},"surface":null,"cave":null,"board":false,"art":{"path":"assets/Objects/Wilderness/Crow.png","frameWidth":32,"frameHeight":32},"palette":{"shadow":"#2f3a47","mid":"#8d9aa8","highlight":"#eef2f6","gamma":0.35},"eliteEligible":false},
    {"id":"gelatinous_cube","name":"Gelatinous Cube","tier":3,"hp":65,"armor":0,"dmg":6,"range":0.6,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":7,"movement":{"pattern":"engulf","speedMetersPerSecond":1.2},"surface":null,"cave":{"minDepth":3,"maxDepth":4,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[129,130,131],"move":[129,130,131]},"left":{"idle":[159,160,161],"move":[159,160,161]},"right":{"idle":[189,190,191],"move":[189,190,191]},"up":{"idle":[219,220,221],"move":[219,220,221]}},"directionSideFacing":"right","bounds":[2,15],"frameMs":180},"artScale":1,"eliteEligible":true,"contactSlow":{"radiusCells":0.6,"speedMul":0.5}},
    {"id":"jellyfish","name":"Jellyfish","tier":2,"hp":28,"armor":0,"dmg":8,"range":0.6,"attackType":"melee","damageIntervalSeconds":7,"windupSeconds":0.3,"attackHits":1,"visionCells":7,"movement":{"pattern":"pursue","speedMetersPerSecond":1.6,"waterOnly":true,"shoreOnly":true},"surface":{"biomes":["SAND"],"minDistance":250,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[387,388,389],"move":[387,388,389]},"left":{"idle":[417,418,419],"move":[417,418,419]},"right":{"idle":[447,448,449],"move":[447,448,449]},"up":{"idle":[477,478,479],"move":[477,478,479]}},"directionSideFacing":"right","bounds":[0,14],"frameMs":180},"artScale":1,"eliteEligible":true,"condition":"jellyfish_stun"},
    {"id":"golden_slime","name":"Golden Slime","tier":3,"hp":48,"armor":0,"dmg":5,"range":0.6,"attackType":"melee","damageIntervalSeconds":2,"windupSeconds":0.3,"attackHits":1,"visionCells":7,"movement":{"pattern":"orbit_trail","speedMetersPerSecond":3,"orbitRadiusCells":1.6},"surface":{"biomes":["WETLAND"],"minDistance":750,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[1206,1207,1208],"move":[1206,1207,1208]},"left":{"idle":[1236,1237,1238],"move":[1236,1237,1238]},"right":{"idle":[1266,1267,1268],"move":[1266,1267,1268]},"up":{"idle":[1296,1297,1298],"move":[1296,1297,1298]}},"directionSideFacing":"right","bounds":[6,16],"frameMs":180},"artScale":1,"eliteEligible":true,"trail":{"durationSeconds":600,"radiusCells":0.22,"rawDps":3,"spacingCells":0.3}},
    {"id":"mimic","name":"Mimic","tier":3,"hp":65,"armor":0,"dmg":24,"range":0.6,"attackType":"melee","damageIntervalSeconds":2,"windupSeconds":0.3,"attackHits":1,"visionCells":7,"movement":{"pattern":"pursue","speedMetersPerSecond":2},"surface":{"biomes":[],"minDistance":0,"maxDistance":null,"time":"any","weight":0},"cave":null,"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[27,28,29],"move":[27,28,29]},"left":{"idle":[57,58,59],"move":[57,58,59]},"right":{"idle":[87,88,89],"move":[87,88,89]},"up":{"idle":[117,118,119],"move":[117,118,119]}},"directionSideFacing":"right","bounds":[0,16],"frameMs":180},"artScale":1,"eliteEligible":false},
    {"id":"wurm","name":"Wurm","tier":3,"hp":55,"armor":0,"dmg":14,"range":0.6,"attackType":"melee","damageIntervalSeconds":2,"windupSeconds":0.3,"attackHits":1,"visionCells":7,"movement":{"pattern":"burrow","speedMetersPerSecond":2.5,"burrowSeconds":[3,7],"surfacedSeconds":[2,4],"emergeRadiusCells":2,"emergeSeconds":0.8},"surface":{"biomes":[],"minDistance":750,"maxDistance":null,"time":"any","weight":0},"cave":null,"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[0,1,2],"move":[0,1,2]},"left":{"idle":[30,31,32],"move":[30,31,32]},"right":{"idle":[60,61,62],"move":[60,61,62]},"up":{"idle":[90,91,92],"move":[90,91,92]}},"directionSideFacing":"right","bounds":[2,16],"frameMs":180},"artScale":1,"eliteEligible":false},
    {"id":"sword_spirit","permanentBuffs":["flight"],"name":"Sword Spirit","tier":3,"hp":32,"armor":0,"dmg":14,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":0.3,"attackHits":1,"visionCells":7,"movement":{"pattern":"orbit_swoop","speedMetersPerSecond":9,"orbitRadiusCells":[1.5,3],"maxLegCells":2.5,"flightSeconds":[0.5,0.8],"pauseSeconds":[0.3,0.6],"swoopEveryLegs":3,"swoopTargetRadiusCells":0.35,"attackCycleSeconds":4,"collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true},"surface":{"biomes":["COMMERCIAL"],"minDistance":750,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":4,"maxDepth":5,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[1089,1090,1091],"move":[1089,1090,1091]},"left":{"idle":[1119,1120,1121],"move":[1119,1120,1121]},"right":{"idle":[1149,1150,1151],"move":[1149,1150,1151]},"up":{"idle":[1179,1180,1181],"move":[1179,1180,1181]}},"directionSideFacing":"right","bounds":[1,14],"frameMs":180},"artScale":1,"eliteEligible":true},
    {"id":"mushroom_monster","name":"Mushroom Monster","tier":2,"hp":30,"armor":0,"dmg":1,"range":3,"attackType":"projectile","projectile":"confusion_puff","minRange":1,"projectileCondition":"confused","projectileSpeedMetersPerSecond":3,"damageIntervalSeconds":6,"windupSeconds":0.7,"attackHits":1,"visionCells":6,"movement":{"pattern":"keep_distance","speedMetersPerSecond":1.6,"preferredDistanceCells":2.5},"meleeWhenCondition":{"id":"confused","minRange":0,"dmg":2,"range":0.6,"damageIntervalSeconds":1.5,"windupSeconds":0.15},"surface":{"biomes":[],"minDistance":250,"maxDistance":null,"time":"any","weight":0},"cave":null,"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[144,145,146],"move":[144,145,146]},"left":{"idle":[174,175,176],"move":[174,175,176]},"right":{"idle":[204,205,206],"move":[204,205,206]},"up":{"idle":[234,235,236],"move":[234,235,236]}},"directionSideFacing":"right","bounds":[2,16],"frameMs":180},"artScale":0.8,"eliteEligible":true},
    {"id":"treant","name":"Treant","tier":2,"hp":60,"armor":2,"dmg":12,"range":0.6,"attackType":"melee","damageIntervalSeconds":3,"windupSeconds":0.6,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":1.5},"surface":{"biomes":[],"minDistance":250,"maxDistance":null,"time":"any","weight":0},"cave":null,"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[483,484,485],"move":[483,484,485]},"left":{"idle":[513,514,515],"move":[513,514,515]},"right":{"idle":[543,544,545],"move":[543,544,545]},"up":{"idle":[573,574,575],"move":[573,574,575]}},"directionSideFacing":"right","bounds":[0,16],"frameMs":180},"artScale":1,"eliteEligible":true,"disguise":{"crop":"shrub","look":"bramble","revealCells":1,"wiggleRadians":0.045,"wigglePeriodMs":1100}},
    {"id":"fire_elemental","name":"Fire Elemental","tier":4,"hp":60,"armor":0,"dmg":10,"range":0.6,"attackType":"melee","damageIntervalSeconds":2.5,"windupSeconds":0.4,"attackHits":1,"visionCells":7,"movement":{"pattern":"pursue","speedMetersPerSecond":2.4},"surface":null,"cave":{"minDepth":5,"maxDepth":5,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/spr_mini_monsters_spritesheet.png","frameWidth":16,"frameHeight":16,"directions":{"down":{"idle":[726,727,728],"move":[726,727,728]},"left":{"idle":[756,757,758],"move":[756,757,758]},"right":{"idle":[786,787,788],"move":[786,787,788]},"up":{"idle":[816,817,818],"move":[816,817,818]}},"directionSideFacing":"right","bounds":[0,15],"frameMs":180},"artScale":1,"eliteEligible":true,"lavaImmune":true,"condition":"burning"},
    // Approved large directional sheets; sizes and combat values share these rows.
    {"id":"bugbear","name":"Bugbear","tier":3,"hp":70,"armor":2,"dmg":14,"range":1,"attackType":"melee","damageIntervalSeconds":3,"windupSeconds":0.8,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":2},"surface":null,"cave":null,"art":{"path":"assets/Enemy/LargeDirectionalV2/bugbear.png","frameWidth":32,"frameHeight":32,"directions":{"up":{"idle":[0],"move":[0,1,2,3],"attack":[4,5,6,7]},"right":{"idle":[8],"move":[8,9,10,11],"attack":[12,13,14,15]},"down":{"idle":[16],"move":[16,17,18,19],"attack":[20,21,22,23]},"left":{"idle":[24],"move":[24,25,26,27],"attack":[28,29,30,31]}},"directionSideFacing":"right","bounds":[8,30],"frameMs":140},"artScale":0.8,"eliteEligible":false},
    {"id":"troll","name":"Troll","tier":2,"hp":60,"armor":1,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":0.8,"attackHits":1,"visionCells":6,"movement":{"pattern":"lumber","speedMetersPerSecond":1.5},"surface":null,"cave":{"minDepth":3,"maxDepth":3,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/LargeDirectionalV2/troll.png","frameWidth":32,"frameHeight":32,"directions":{"up":{"idle":[0],"move":[0,1,2,3],"attack":[4,5,6,7]},"right":{"idle":[8],"move":[8,9,10,11],"attack":[12,13,14,15]},"down":{"idle":[16],"move":[16,17,18,19],"attack":[20,21,22,23]},"left":{"idle":[24],"move":[24,25,26,27],"attack":[28,29,30,31]}},"directionSideFacing":"right","bounds":[6,28],"frameMs":140},"artScale":0.8,"eliteEligible":false},
    {"id":"giant_bear","name":"Giant Bear","tier":3,"hp":80,"armor":1,"dmg":15,"range":1,"attackType":"melee","damageIntervalSeconds":3,"windupSeconds":0.8,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":2.0},"surface":{"biomes":["FOREST"],"minDistance":750,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/LargeDirectionalV2/giant-bear.png","frameWidth":32,"frameHeight":32,"directions":{"up":{"idle":[0],"move":[0,1,2,3],"attack":[4,5,6,7]},"right":{"idle":[8],"move":[8,9,10,11],"attack":[12,13,14,15]},"down":{"idle":[16],"move":[16,17,18,19],"attack":[20,21,22,23]},"left":{"idle":[24],"move":[24,25,26,27],"attack":[28,29,30,31]}},"directionSideFacing":"right","bounds":[4,29],"frameMs":140},"artScale":0.8,"eliteEligible":false},
    {"id":"ogre","name":"Ogre","tier":3,"hp":90,"armor":1,"dmg":16,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":0.8,"attackHits":1,"visionCells":6,"movement":{"pattern":"lumber","speedMetersPerSecond":1.1},"surface":{"biomes":["RESIDENTIAL"],"minDistance":750,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/LargeDirectionalV2/ogre.png","frameWidth":32,"frameHeight":32,"directions":{"up":{"idle":[0],"move":[0,1,2,3],"attack":[4,5,6,7]},"right":{"idle":[8],"move":[8,9,10,11],"attack":[12,13,14,15]},"down":{"idle":[16],"move":[16,17,18,19],"attack":[20,21,22,23]},"left":{"idle":[24],"move":[24,25,26,27],"attack":[28,29,30,31]}},"directionSideFacing":"right","bounds":[8,29],"frameMs":140},"artScale":0.8,"eliteEligible":false},
    {"id":"giant_reaper","name":"Giant Reaper","tier":3,"hp":65,"armor":1,"dmg":16,"range":1,"attackType":"melee","damageIntervalSeconds":3,"windupSeconds":0.8,"attackHits":1,"visionCells":6,"movement":{"pattern":"pursue","speedMetersPerSecond":1.6},"surface":{"biomes":[],"minDistance":750,"maxDistance":null,"time":"any","weight":0},"cave":null,"art":{"path":"assets/Enemy/LargeDirectionalV2/giant-reaper.png","frameWidth":32,"frameHeight":32,"directions":{"up":{"idle":[0],"move":[0,1,2,3],"attack":[4,5,6,7]},"right":{"idle":[8],"move":[8,9,10,11],"attack":[12,13,14,15]},"down":{"idle":[16],"move":[16,17,18,19],"attack":[20,21,22,23]},"left":{"idle":[24],"move":[24,25,26,27],"attack":[28,29,30,31]}},"directionSideFacing":"right","bounds":[4,27],"frameMs":140},"artScale":0.8,"eliteEligible":false},
  ];
  const ALL = Object.fromEntries(ROWS.map(row => [row.id, row]));
  const SURFACE_TIERS = [{"minDistance":0,"maxDistance":250,"tierWeights":{"1":1}},{"minDistance":250,"maxDistance":750,"tierWeights":{"1":0.6,"2":0.4}},{"minDistance":750,"maxDistance":1500,"tierWeights":{"1":0.3,"2":0.5,"3":0.2}},{"minDistance":1500,"maxDistance":null,"tierWeights":{"1":0.2,"2":0.4,"3":0.4}}];
  const GHOST_SCALING = {"cadenceSeconds":300,"jitterSeconds":60,"minCryptDepth":3,"rows":[{"zone":"surface_night","minDepth":0,"maxDepth":0,"groupMin":1,"groupMax":3,"nearMax":6,"sizeMultiplier":1},{"zone":"dungeon","minDepth":2,"maxDepth":3,"groupMin":1,"groupMax":3,"nearMax":6,"sizeMultiplier":1},{"zone":"dungeon","minDepth":4,"maxDepth":5,"groupMin":2,"groupMax":4,"nearMax":8,"sizeMultiplier":1},{"zone":"dungeon","minDepth":6,"maxDepth":null,"groupMin":2,"groupMax":4,"nearMax":8,"sizeMultiplier":1.5,"powerMultiplier":2}],"stats":"Crypt pockets select dungeon ghosts from depth 3; bands apply to odd and even depths. Enlarged ghosts have double HP and touch damage; speed and contact range stay unchanged. White:pink weight 2:1 from haunted depth6. Both colours receive the size multiplier. No additional unlimited growth below depth6.","multiplayer":"Same group count and visible size for all players; Hard does not alter ghost spawns."};
  function get(kind) { return ALL[kind] || null; }
  function baseKind(kind) { return get(kind)?.variantOf || kind; }
  // A foe that never moves off its seat (its row's movement.rooted — the
  // plants). Fine on a road variant's stretch; never a building's garrison.
  function isRooted(kind) { return get(kind)?.movement?.rooted === true; }
  function ghostProfile(depth) {
    return GHOST_SCALING.rows.find(r => depth >= r.minDepth && (r.maxDepth == null || depth <= r.maxDepth)) || null;
  }
  const api = { ALL, ROWS, SURFACE_TIERS, GHOST_SCALING, get, baseKind, isRooted, ghostProfile, GIANT_SCALE: 1.6, MINI_SCALE: 0.65 };
  root.EnemyRoster = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})(typeof window !== 'undefined' ? window : globalThis);
