// Approved enemy roster: actual shared stats, before Elite and player-side difficulty.
// Combat, art, behaviour and spawn eligibility resolve the same row. No cave doubling.
(function (root) {
  'use strict';
  const ROWS = [
    {"id":"slime","name":"Green Slime","tier":1,"hp":10,"armor":0,"dmg":1,"range":1,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":4,"movement":{"pattern":"ooze","speedMetersPerSecond":1.1,"chargeSpeedMetersPerSecond":1.6},"surface":{"biomes":["GRASS","PARK","FARMLAND","WETLAND"],"minDistance":0,"maxDistance":null,"time":"any","weight":5},"cave":{"minDepth":1,"maxDepth":2,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime/SlimeIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"cave_slime","name":"Cave Slime","tier":1,"hp":24,"armor":0,"dmg":6,"range":1,"attackType":"melee","damageIntervalSeconds":3,"windupSeconds":0.6,"attackHits":1,"visionCells":5,"movement":{"pattern":"ooze","speedMetersPerSecond":1.15},"surface":null,"cave":{"minDepth":1,"maxDepth":3,"weight":5,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime/Reskin/BlueSlimeIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"bat","name":"Bat","tier":1,"hp":16,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":4.5,"windupSeconds":0.35,"attackHits":1,"visionCells":7,"movement":{"pattern":"orbit_swoop","source":"_wildCrowTick","orbitRadiusCells":[1.5,3.5],"maxLegCells":2.5,"flightSeconds":[0.8,1.2],"pauseSeconds":[0.6,1],"swoopEveryLegs":2,"swoopTargetRadiusCells":0.35,"easing":"quadratic_in_out","collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true,"attackCycleSeconds":4.5,"hitPolicy":"One successful contact per swoop; no contact drain while orbiting. Recovery and cooldown are included in the full attack cycle.","speedMetersPerSecond":5.5,"speedMeaning":"Peak instantaneous flight speed; eased leg duration must be at least 2*distance/speed."},"surface":{"biomes":["FOREST","ORCHARD","ROCK"],"minDistance":0,"maxDistance":null,"time":"night","weight":2},"cave":{"minDepth":1,"maxDepth":3,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Bat/BatIdleFont.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"purple_slime","name":"Purple Slime","tier":1,"hp":16,"armor":0,"dmg":5,"range":1,"attackType":"melee","damageIntervalSeconds":1.4,"windupSeconds":0.15,"attackHits":1,"visionCells":6,"movement":{"pattern":"hop_retreat","retreatDistanceFraction":0.75,"speedMetersPerSecond":2.1},"surface":null,"cave":{"minDepth":2,"maxDepth":4,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Purple Slime.png","frameWidth":32,"frameHeight":32},"eliteEligible":true},
    {"id":"spider","name":"Spider","tier":1,"hp":13,"armor":0,"dmg":5,"range":1,"attackType":"melee","damageIntervalSeconds":1.2,"windupSeconds":0.1,"attackHits":1,"visionCells":6,"movement":{"pattern":"scuttle_pause","scuttleSeconds":1.2,"pauseSeconds":0.35,"approachAngleJitterRadians":0.6,"speedMetersPerSecond":3.2},"surface":{"biomes":["FOREST","ORCHARD","WETLAND"],"minDistance":0,"maxDistance":null,"time":"any","weight":2},"cave":{"minDepth":2,"maxDepth":4,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Spider/SpiderIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"zombie","name":"Zombie","tier":2,"hp":40,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1,"attackHits":1,"visionCells":5,"movement":{"pattern":"pursue","speedMetersPerSecond":1.2},"surface":{"biomes":["WETLAND","RESIDENTIAL","INDUSTRIAL"],"minDistance":250,"maxDistance":null,"time":"night","weight":3},"cave":{"minDepth":2,"maxDepth":5,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Zombie/ZombieIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"plant","name":"Plant","tier":2,"hp":43,"armor":0,"dmg":8,"range":2,"attackType":"projectile","damageIntervalSeconds":2.5,"windupSeconds":0.5,"attackHits":1,"visionCells":6,"movement":{"pattern":"anchor_spit","preferredDistanceCells":2,"speedMetersPerSecond":1.1},"surface":{"biomes":["GRASS","PARK","FARMLAND","FOREST","ORCHARD"],"minDistance":250,"maxDistance":null,"time":"any","weight":3},"cave":{"minDepth":3,"maxDepth":5,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Plant/PlantIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"skeleton","name":"Skeleton","tier":2,"hp":16,"armor":2,"dmg":6,"range":1,"attackType":"melee","damageIntervalSeconds":1.6,"windupSeconds":0.2,"attackHits":1,"visionCells":7,"movement":{"pattern":"pursue","speedMetersPerSecond":2},"surface":{"biomes":["ROCK","SAND","INDUSTRIAL"],"minDistance":250,"maxDistance":null,"time":"any","weight":2},"cave":{"minDepth":3,"maxDepth":6,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Skeleton/SkeletonIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"goblin","name":"Goblin","tier":3,"hp":48,"armor":0,"dmg":9,"range":1,"attackType":"melee","damageIntervalSeconds":1.8,"windupSeconds":0.25,"attackHits":1,"visionCells":9,"movement":{"pattern":"pursue_retreat","retreatDistanceFraction":0.5,"speedMetersPerSecond":3.5},"surface":{"biomes":["FOREST","ROCK","COMMERCIAL","INDUSTRIAL"],"minDistance":750,"maxDistance":null,"time":"any","weight":3},"cave":{"minDepth":3,"maxDepth":6,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Goblin.png","frameWidth":32,"frameHeight":32},"eliteEligible":true},
    {"id":"goblin_archer","name":"Goblin Archer","tier":3,"hp":57,"armor":0,"dmg":10,"range":3,"attackType":"projectile","damageIntervalSeconds":3.5,"windupSeconds":0.7,"attackHits":1,"visionCells":10,"movement":{"pattern":"keep_distance","preferredDistanceCells":3,"speedMetersPerSecond":2.8},"surface":{"biomes":["FOREST","ROCK","COMMERCIAL","INDUSTRIAL"],"minDistance":750,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":4,"maxDepth":7,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Goblin Archer.png","frameWidth":32,"frameHeight":32},"eliteEligible":true},
    {"id":"goblin_trapper","name":"Goblin Trapper","tier":3,"hp":40,"armor":0,"dmg":0,"range":3,"attackType":"trap","damageIntervalSeconds":10,"windupSeconds":0.6,"attackHits":1,"visionCells":9,"movement":{"pattern":"keep_distance","preferredDistanceCells":3,"retreatDistanceFraction":0.5,"speedMetersPerSecond":2.7},"surface":null,"cave":{"minDepth":4,"maxDepth":7,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Goblin.png","frameWidth":32,"frameHeight":32,"tint":"#ff4a3a"},"tint":"#ff4a3a","eliteEligible":false},
    {"id":"vampire_bat","name":"Vampire Bat","tier":3,"hp":39,"armor":0,"dmg":14,"range":1,"attackType":"melee","damageIntervalSeconds":3.6,"windupSeconds":0.3,"attackHits":1,"visionCells":8,"movement":{"pattern":"orbit_swoop","source":"_wildCrowTick","orbitRadiusCells":[1.25,3],"maxLegCells":2.5,"flightSeconds":[0.65,0.95],"pauseSeconds":[0.4,0.7],"swoopEveryLegs":2,"swoopTargetRadiusCells":0.35,"easing":"quadratic_in_out","collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true,"attackCycleSeconds":3.6,"hitPolicy":"One successful contact per swoop; no contact drain while orbiting. Recovery and cooldown are included in the full attack cycle.","speedMetersPerSecond":6,"speedMeaning":"Peak instantaneous flight speed; eased leg duration must be at least 2*distance/speed."},"surface":null,"cave":{"minDepth":4,"maxDepth":7,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Bat/Reskin/VampireBatIdleFront.png","frameWidth":16,"frameHeight":16},"palette":{"shadow":"#164e61","mid":"#34e7ee","highlight":"#ecffff","gamma":0.4},"eliteEligible":true},
    {"id":"brute","name":"Brute","tier":4,"hp":95,"armor":0,"dmg":16,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1.1,"attackHits":1,"visionCells":5,"movement":{"pattern":"lumber","speedMetersPerSecond":1.3},"surface":null,"cave":{"minDepth":5,"maxDepth":8,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Brute/BruteIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":false},
    {"id":"poison_spider","name":"Poison Spider","tier":4,"hp":61,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":1.4,"windupSeconds":0.2,"attackHits":1,"visionCells":7,"movement":{"pattern":"scuttle_pause","scuttleSeconds":1.4,"pauseSeconds":0.25,"approachAngleJitterRadians":0.8,"speedMetersPerSecond":3.8},"surface":null,"cave":{"minDepth":5,"maxDepth":8,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Spider/Reskin/PoisonSpiderIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"dryad","name":"Dryad","tier":4,"hp":61,"armor":0,"dmg":14,"range":3,"attackType":"projectile","damageIntervalSeconds":3,"windupSeconds":0.7,"attackHits":1,"visionCells":8,"movement":{"pattern":"strafe_cast","preferredDistanceCells":3,"strafeAngleRadians":0.6,"speedMetersPerSecond":2.2},"surface":null,"cave":{"minDepth":5,"maxDepth":8,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Succubus/Reskin/DryadIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"lich","name":"Lich","tier":5,"hp":52,"armor":6,"dmg":16,"range":3,"attackType":"projectile","damageIntervalSeconds":4,"windupSeconds":0.8,"attackHits":1,"visionCells":8,"movement":{"pattern":"strafe_cast","preferredDistanceCells":3,"speedMetersPerSecond":1.8},"surface":null,"cave":{"minDepth":6,"maxDepth":null,"weight":3,"depthRule":"any"},"art":{"path":"assets/Enemy/Skeleton/Reskin/DrySkeletonIdleFront.png","frameWidth":16,"frameHeight":16},"palette":{"shadow":"#102b18","mid":"#71dc34","highlight":"#e6ffc0"},"aura":{"source":"Potion of Blight","radiusCells":1.5,"rawDps":2,"mitigationPacketSeconds":1,"healsSelf":false,"stacks":"Independent sources add; at most one aura contribution per enemy per target.","damageType":"energy","rule":"Mitigate a one-second damage packet with Combat.mitigate, then accumulate the resulting rate × dt. Never apply the minimum-hit floor per rendered frame. Apply player Hard penalty after mitigation."},"projectile":"blight_magic","eliteEligible":true},
    {"id":"bone_plant","name":"Bone Plant","tier":5,"hp":77,"armor":4,"dmg":18,"range":3,"attackType":"projectile","damageIntervalSeconds":4,"windupSeconds":0.8,"attackHits":1,"visionCells":8,"movement":{"pattern":"anchor_spit","preferredDistanceCells":3,"speedMetersPerSecond":1.1},"surface":null,"cave":{"minDepth":6,"maxDepth":null,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Plant/Reskin/BonePlantIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"fiend","name":"Fiend","tier":5,"hp":73,"armor":0,"dmg":13,"range":1,"attackType":"melee","damageIntervalSeconds":1.25,"windupSeconds":0.15,"attackHits":1,"visionCells":8,"movement":{"pattern":"lunge_recover","lungeSeconds":0.6,"lungeWindupSeconds":0.5,"lungeCooldownSeconds":4,"speedMetersPerSecond":3.5,"lungeSpeedMetersPerSecond":5.5},"surface":null,"cave":{"minDepth":6,"maxDepth":null,"weight":2,"depthRule":"any"},"art":{"path":"assets/Enemy/Zombie/Reskin/FiendIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"succubus","name":"Succubus","tier":6,"hp":137,"armor":2,"dmg":18,"range":4,"attackType":"projectile","damageIntervalSeconds":3,"windupSeconds":0.6,"attackHits":1,"visionCells":10,"movement":{"pattern":"strafe_cast","preferredDistanceCells":4,"strafeAngleRadians":0.9,"speedMetersPerSecond":2.6},"surface":null,"cave":{"minDepth":7,"maxDepth":null,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Succubus/SuccubusIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":true},
    {"id":"hell_brute","name":"Hell Brute","tier":7,"hp":225,"armor":0,"dmg":28,"range":1,"attackType":"melee","damageIntervalSeconds":5,"windupSeconds":1.5,"attackHits":1,"visionCells":6,"movement":{"pattern":"lumber","speedMetersPerSecond":1.1},"surface":null,"cave":{"minDepth":8,"maxDepth":null,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Brute/Reskin/HellBruteIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":false},
    {"id":"ghost","name":"Ghost","tier":3,"hp":20,"armor":0,"dmg":12,"range":1,"attackType":"touch","damageIntervalSeconds":null,"windupSeconds":0,"attackHits":1,"visionCells":6,"movement":{"pattern":"ghost_glide","speedMetersPerSecond":3,"collision":"existing_ghost_rules"},"surface":{"biomes":["GRASS","FOREST","ROCK","SAND","FARMLAND","RESIDENTIAL","PARK","COMMERCIAL","INDUSTRIAL","WETLAND","ORCHARD"],"minDistance":750,"maxDistance":null,"time":"night","weight":1},"cave":{"minDepth":2,"maxDepth":null,"weight":2,"depthRule":"even"},"art":{"path":"assets/Enemy/Ghost/GhostIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":false},
    {"id":"pink_ghost","name":"Pink Ghost","tier":5,"hp":30,"armor":0,"dmg":16,"range":1,"attackType":"touch","damageIntervalSeconds":null,"windupSeconds":0,"attackHits":1,"visionCells":8,"movement":{"pattern":"ghost_glide","speedMetersPerSecond":3.5,"collision":"existing_ghost_rules"},"surface":null,"cave":{"minDepth":6,"maxDepth":null,"weight":1,"depthRule":"even"},"art":{"path":"assets/Enemy/Ghost/Reskin/PinkGhostIdleFront.png","frameWidth":16,"frameHeight":16},"eliteEligible":false},
    {"id":"mini_slime","name":"Mini Green Slime","tier":1,"hp":5,"armor":0,"dmg":1,"range":1,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":4,"movement":{"pattern":"ooze","speedMetersPerSecond":1.23},"surface":{"biomes":["GRASS","PARK","FARMLAND"],"minDistance":0,"maxDistance":null,"time":"any","weight":2},"cave":{"minDepth":1,"maxDepth":2,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime/SlimeIdleFront.png","frameWidth":16,"frameHeight":16},"variantOf":"slime","variantType":"Mini","eliteEligible":false},
    {"id":"mini_spider","name":"Mini Spider","tier":1,"hp":11,"armor":0,"dmg":5,"range":1,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0.1,"attackHits":1,"visionCells":6,"movement":{"pattern":"scuttle_pause","scuttleSeconds":1.2,"pauseSeconds":0.35,"approachAngleJitterRadians":0.6,"speedMetersPerSecond":3.58},"surface":{"biomes":["FOREST","ORCHARD"],"minDistance":0,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":1,"maxDepth":3,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Spider/SpiderIdleFront.png","frameWidth":16,"frameHeight":16},"variantOf":"spider","variantType":"Mini","eliteEligible":false},
    {"id":"giant_slime","name":"Giant Green Slime","tier":2,"hp":31,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":3.6,"windupSeconds":0.7,"attackHits":1,"visionCells":4,"movement":{"pattern":"ooze","speedMetersPerSecond":1.1},"surface":{"biomes":["WETLAND","PARK","FARMLAND"],"minDistance":250,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":3,"maxDepth":5,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime/SlimeIdleFront.png","frameWidth":16,"frameHeight":16},"variantOf":"slime","variantType":"Giant","eliteEligible":false},
    {"id":"giant_spider","name":"Giant Spider","tier":3,"hp":39,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":2.2,"windupSeconds":0.35,"attackHits":1,"visionCells":6,"movement":{"pattern":"scuttle_pause","scuttleSeconds":1.2,"pauseSeconds":0.35,"approachAngleJitterRadians":0.6,"speedMetersPerSecond":2.72},"surface":{"biomes":["FOREST","ORCHARD","WETLAND"],"minDistance":750,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":4,"maxDepth":6,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Spider/SpiderIdleFront.png","frameWidth":16,"frameHeight":16},"variantOf":"spider","variantType":"Giant","eliteEligible":false},
    {"id":"giant_skeleton","name":"Giant Skeleton","tier":3,"hp":37,"armor":2,"dmg":12,"range":1,"attackType":"melee","damageIntervalSeconds":2.6,"windupSeconds":0.5,"attackHits":1,"visionCells":7,"movement":{"pattern":"pursue","speedMetersPerSecond":1.7},"surface":{"biomes":["ROCK","SAND","INDUSTRIAL"],"minDistance":1500,"maxDistance":null,"time":"any","weight":1},"cave":{"minDepth":5,"maxDepth":8,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Skeleton/SkeletonIdleFront.png","frameWidth":16,"frameHeight":16},"variantOf":"skeleton","variantType":"Giant","eliteEligible":false},
    {"id":"giant_cave_slime","name":"Giant Cave Slime","tier":3,"hp":66,"armor":0,"dmg":12,"range":1,"attackType":"melee","damageIntervalSeconds":3.6,"windupSeconds":0.7,"attackHits":1,"visionCells":5,"movement":{"pattern":"ooze","speedMetersPerSecond":1.1},"surface":null,"cave":{"minDepth":3,"maxDepth":5,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Slime/Reskin/BlueSlimeIdleFront.png","frameWidth":16,"frameHeight":16},"variantOf":"cave_slime","variantType":"Giant","eliteEligible":false},
    {"id":"mini_vampire_bat","name":"Mini Vampire Bat","tier":2,"hp":31,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":3.6,"windupSeconds":0.25,"attackHits":1,"visionCells":8,"movement":{"pattern":"orbit_swoop","source":"_wildCrowTick","orbitRadiusCells":[1.25,3],"maxLegCells":2.5,"flightSeconds":[0.5652173913043479,0.8260869565217391],"pauseSeconds":[0.4,0.7],"swoopEveryLegs":2,"swoopTargetRadiusCells":0.35,"easing":"quadratic_in_out","collision":"swept_solid_obstacles","flightOnlyOverLowObstacles":true,"attackCycleSeconds":3.6,"hitPolicy":"One successful contact per swoop; no contact drain while orbiting. Recovery and cooldown are included in the full attack cycle.","speedMetersPerSecond":6,"speedMeaning":"Peak instantaneous flight speed; eased leg duration must be at least 2*distance/speed."},"surface":null,"cave":{"minDepth":3,"maxDepth":5,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Bat/Reskin/VampireBatIdleFront.png","frameWidth":16,"frameHeight":16},"palette":{"shadow":"#164e61","mid":"#34e7ee","highlight":"#ecffff","gamma":0.4},"variantOf":"vampire_bat","variantType":"Mini","eliteEligible":false},
    {"id":"giant_lich","name":"Giant Lich","tier":7,"hp":110,"armor":6,"dmg":24,"range":4,"attackType":"projectile","damageIntervalSeconds":5,"windupSeconds":1,"attackHits":1,"visionCells":9,"movement":{"pattern":"strafe_cast","preferredDistanceCells":4,"speedMetersPerSecond":1.53},"surface":null,"cave":{"minDepth":8,"maxDepth":null,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Skeleton/Reskin/DrySkeletonIdleFront.png","frameWidth":16,"frameHeight":16},"palette":{"shadow":"#102b18","mid":"#71dc34","highlight":"#e6ffc0"},"aura":{"source":"Potion of Blight","radiusCells":2.4,"rawDps":2,"mitigationPacketSeconds":1,"healsSelf":false,"stacks":"Independent sources add; at most one aura contribution per enemy per target.","damageType":"energy","rule":"Mitigate a one-second damage packet with Combat.mitigate, then accumulate the resulting rate × dt. Never apply the minimum-hit floor per rendered frame. Apply player Hard penalty after mitigation."},"projectile":"blight_magic","variantOf":"lich","variantType":"Giant","eliteEligible":false},
    {"id":"moss_slime","name":"Moss Green Slime","tier":1,"hp":10,"armor":0,"dmg":1,"range":1,"attackType":"melee","damageIntervalSeconds":1,"windupSeconds":0,"attackHits":1,"visionCells":4,"movement":{"pattern":"ooze","speedMetersPerSecond":1.1},"surface":{"biomes":["FOREST","ORCHARD"],"minDistance":0,"maxDistance":null,"time":"any","weight":2},"cave":null,"art":{"path":"assets/Enemy/Slime/SlimeIdleFront.png","frameWidth":16,"frameHeight":16,"tint":"#8ea660"},"tint":"#8ea660","variantOf":"slime","variantType":"Tint","eliteEligible":true},
    {"id":"sand_skeleton","name":"Sand Skeleton","tier":2,"hp":16,"armor":2,"dmg":6,"range":1,"attackType":"melee","damageIntervalSeconds":1.6,"windupSeconds":0.2,"attackHits":1,"visionCells":7,"movement":{"pattern":"pursue","speedMetersPerSecond":2},"surface":{"biomes":["SAND"],"minDistance":250,"maxDistance":null,"time":"any","weight":2},"cave":null,"art":{"path":"assets/Enemy/Skeleton/SkeletonIdleFront.png","frameWidth":16,"frameHeight":16,"tint":"#d4b276"},"tint":"#d4b276","variantOf":"skeleton","variantType":"Tint","eliteEligible":true},
    {"id":"marsh_zombie","name":"Marsh Zombie","tier":2,"hp":40,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1,"attackHits":1,"visionCells":5,"movement":{"pattern":"pursue","speedMetersPerSecond":1.2},"surface":{"biomes":["WETLAND"],"minDistance":250,"maxDistance":null,"time":"night","weight":2},"cave":null,"art":{"path":"assets/Enemy/Zombie/ZombieIdleFront.png","frameWidth":16,"frameHeight":16,"tint":"#819d78"},"tint":"#819d78","variantOf":"zombie","variantType":"Tint","eliteEligible":true},
    {"id":"copper_plant","name":"Copper Plant","tier":2,"hp":43,"armor":0,"dmg":8,"range":2,"attackType":"projectile","damageIntervalSeconds":2.5,"windupSeconds":0.5,"attackHits":1,"visionCells":6,"movement":{"pattern":"anchor_spit","preferredDistanceCells":2,"speedMetersPerSecond":1.1},"surface":{"biomes":["FARMLAND","ORCHARD"],"minDistance":250,"maxDistance":null,"time":"any","weight":1},"cave":null,"art":{"path":"assets/Enemy/Plant/PlantIdleFront.png","frameWidth":16,"frameHeight":16,"tint":"#c68f60"},"palette":{"shadow":"#351108","mid":"#e66b13","highlight":"#ffe6a6"},"variantOf":"plant","variantType":"Tint","eliteEligible":true},
    {"id":"ash_zombie","name":"Ash Zombie","tier":2,"hp":40,"armor":0,"dmg":10,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1,"attackHits":1,"visionCells":5,"movement":{"pattern":"pursue","speedMetersPerSecond":1.2},"surface":null,"cave":{"minDepth":3,"maxDepth":6,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Zombie/ZombieIdleFront.png","frameWidth":16,"frameHeight":16},"tint":"#9aa3b2","variantOf":"zombie","variantType":"Tint","eliteEligible":true},
    {"id":"obsidian_brute","name":"Obsidian Brute","tier":4,"hp":95,"armor":0,"dmg":16,"range":1,"attackType":"melee","damageIntervalSeconds":4,"windupSeconds":1.1,"attackHits":1,"visionCells":5,"movement":{"pattern":"lumber","speedMetersPerSecond":1.3},"surface":null,"cave":{"minDepth":6,"maxDepth":9,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Brute/BruteIdleFront.png","frameWidth":16,"frameHeight":16},"tint":"#8386a8","variantOf":"brute","variantType":"Tint","eliteEligible":false},
    {"id":"giant_plant","name":"Giant Plant","tier":3,"hp":57,"armor":0,"dmg":14,"range":3,"attackType":"projectile","damageIntervalSeconds":5,"windupSeconds":1,"attackHits":1,"visionCells":7,"movement":{"pattern":"anchor_spit","preferredDistanceCells":3,"speedMetersPerSecond":1.1},"surface":null,"cave":{"minDepth":4,"maxDepth":7,"weight":1,"depthRule":"any"},"art":{"path":"assets/Enemy/Plant/PlantIdleFront.png","frameWidth":16,"frameHeight":16},"variantOf":"plant","variantType":"Giant","eliteEligible":false}
  ];
  const ALL = Object.fromEntries(ROWS.map(row => [row.id, row]));
  const SURFACE_TIERS = [{"minDistance":0,"maxDistance":250,"tierWeights":{"1":1}},{"minDistance":250,"maxDistance":750,"tierWeights":{"1":0.6,"2":0.4}},{"minDistance":750,"maxDistance":1500,"tierWeights":{"1":0.3,"2":0.5,"3":0.2}},{"minDistance":1500,"maxDistance":null,"tierWeights":{"1":0.2,"2":0.4,"3":0.4}}];
  const GHOST_SCALING = {"cadenceSeconds":300,"jitterSeconds":60,"hauntedDepthEvery":2,"rows":[{"zone":"surface_night","minDepth":0,"maxDepth":0,"groupMin":1,"groupMax":3,"nearMax":6,"sizeMultiplier":1},{"zone":"dungeon","minDepth":2,"maxDepth":2,"groupMin":1,"groupMax":3,"nearMax":6,"sizeMultiplier":1},{"zone":"dungeon","minDepth":4,"maxDepth":4,"groupMin":2,"groupMax":4,"nearMax":8,"sizeMultiplier":1},{"zone":"dungeon","minDepth":6,"maxDepth":null,"groupMin":2,"groupMax":4,"nearMax":8,"sizeMultiplier":1.5}],"stats":"Size is visual only: keep touch damage, HP, speed and contact range unchanged. White:pink weight 2:1 from haunted depth6. Both colours receive the size multiplier. No additional unlimited growth below depth6.","multiplayer":"Same group count and visible size for all players; Hard does not alter ghost spawns."};
  function get(kind) { return ALL[kind] || null; }
  function baseKind(kind) { return get(kind)?.variantOf || kind; }
  function ghostProfile(depth) {
    return GHOST_SCALING.rows.find(r => depth >= r.minDepth && (r.maxDepth == null || depth <= r.maxDepth)) || null;
  }
  const api = { ALL, ROWS, SURFACE_TIERS, GHOST_SCALING, get, baseKind, ghostProfile, GIANT_SCALE: 1.6, MINI_SCALE: 0.65 };
  root.EnemyRoster = api;
  if (typeof module !== 'undefined' && module.exports) module.exports = api;
})(typeof window !== 'undefined' ? window : globalThis);
