// Books are independent excerpts: scholars may quote any page before the story reveals its secrets.
// Keep bookmark order and shared ITEM_GUIDE_TIPS references stable.
const PLAY_TIPS = [
  "I have kept our key. When someone mends our house, I want the children to open the door themselves.",
  "Leave weary hands to rest awhile. Your strength returns even while you are away. The work will wait; I promise.",
  "We heard no army coming. By dawn there were no roofs. Those who saw it called it the Warmonger.",
  "Only beneath your own roof can you sink into the deep rest of home. A campfire warms tired hands until they are ready to work again.",
  "I saw a figure watching me from an empty window. By morning, fresh footprints ended at the wall beneath it.",
  "Finish the work before you settle into a proper rest. I cannot sleep with half a wall leaning over me.",
  "I know the shape of the missing letters. Why can I no longer remember the name?",
  "Bring what you want to sell home to your trailer. Hold it out to the wandering survivors; they will pay for it, one piece at a time.",
  "We had lost every tool. Our bare hands still did the work.",
  "Below ground, your light dwindles with every descent. Overwhelmed by the deeper dark.",
  "Your wandering shadow can scout ahead. It cannot put your weight behind a blow. Plant your own boots where the fighting is. Strike true.",
  "A wounded goblin may still swing. Record observations from a safe distance. If the subject approaches, abandon the notebook.",
  "One task, then the next. That is how we built our house. I cannot face rebuilding it all yet. Today, just the door. I kept the hinges.",
  "ROAD WARDEN’S NOTICE: If caught in a snare, move clear immediately. Remaining within its jaws will cause further injury.",
  ITEM_GUIDE_TIPS.trap_disarm_kit,
  "Stay on the pavement beside a busy road to escape a chase. Never step into the road to play.",
  "Reach things across a street with the game's stick. Never enter the road to collect them.",
  "The game pauses while you travel faster than a run. Play only when you are safely on foot.",
  "On hot days, carry water, stay in the shade and rest often.",
  "After nightfall, I hear ghosts outside the tent. They make no footfalls. I wish they did.",
  "Pull the weeds first, love. The hoe needs clear soil. Your father always tried to hurry that part.",
  "Water before you leave. The crop keeps growing while you are away.",
  "Packing list: Antidote. The purple slime's sickness came home with me last time.",
  "A seed in the harvest! I had almost forgotten that the field could give us another spring.",
  "Bring stone to the ruined house. I can still see where the roof belongs.",
  "The first house we restored became our smithy. I stood outside and listened to the hammer. We had been quiet for so long.",
  "I plant near Home now. Let the raiders go hungry for once.",
  ITEM_GUIDE_TIPS.scarecrow,
  "Observation: merely standing beside a wild slime drains one's strength. Further observation postponed.",
  "The biting plants cannot leave their roots. Keep clear of them, and let them bite the weather.",
  "Strike a slime and it rushes you. Be ready.",
  "Close combat: get nice and close to make your sword count. Remember, that puts the enemy close to you. Strike true!",
  "The creatures followed me as far as Home. There they turned away. I slept against the door.",
  "A first taste of something new leaves a lasting strength. I have begun to keep a little food for visitors, in case they have never tasted it either.",
  "Wrong tool? Perhaps. But I finished the job with it. Took patience, and most of the afternoon.",
  "The old car park has its X, like all the others. Treasure underneath. Strange what survives a kingdom.",
  "So much buried in the shore sand. I came to find shells and went home bent beneath my bag.",
  "Went back to the waterline another day. More gifts from the sea. It has a better memory than the people who owe me money.",
  "A fine gem above a chest promises fine things inside. I trust that sign more than any merchant's smile.",
  "One chest alone shone brighter than the crowded crates. Fewer neighbours, better prospects.",
  "Plain crate. Emptied. Returned later: full again.",
  "Barrel inventory: hollow, hollow, hollow. Whoever stocked this depot had a very light hand.",
  "Returned to the pot of gold another day. Fresh coins. I have crossed out my complaint about the empty pot.",
  "Borrowed swiftness at the courier's post. My wandering double raced ahead; for a moment I felt young by association.",
  "A glow lingered above the unopened gift. I almost walked past. These days I look twice at anything gentle.",
  "I lifted a stone and found a gemfruit beneath. My mother would have called that payment for the effort.",
  "An unfamiliar thing in my palm, and a memory stirred. I could feel it coming before I knew its name.",
  "Shimmering flower: sold above the price of its plain neighbour.",
  "I went back to the park shrine another day. Another gift waited. Someone, or something, still expects us.",
  "Do not disturb a headstone lightly. I woke a ghost, and had no apology it would hear.",
  "At the grove’s heart, a richer chest. I left my pack beside it and sat on the ground. Nothing stirred between the trees. I had not felt safe enough to sit for days.",
  "Lost another fine fish to this poor rod. I'll return with better tackle. The fish can enjoy its victory until then.",
  "Gold on the water. A shiny fish beneath. For once, my brother's fishing story was true.",
  "Heavy line. Splendid catch. Slime. I shall tell my brother it was a fish.",
  "The fish were gone, but I cast again. A little treasure came up. Supper remains an unsolved problem.",
  "The hoe struck something buried. We had been calling this empty ground.",
  "Find a door whose number ends in nine. There will be a smith behind it. Tell them Brann sent you.",
  "Every shop we restore has something new to sell. I used to complain about shopping for the family.",
  "I took the household exactly what its wishlist asked for. They paid generously, and called me by my name.",
  "Their wishlist was unchanged when I returned. They had waited for my bundle. I had not expected anyone to wait for me.",
  "After many deliveries, the newly restored households asked for finer crops. We are beginning to want things again.",
  "Deal with me as often as you like. Ask me to look again and my price for looking climbs, though it softens with each hour that passes.",
  ITEM_GUIDE_TIPS.flowers,
  "The fort's reels gave me matching pictures and a prize. I have omitted the preceding losses from this account.",
  "Our reclaimed castle offers a favour morning and evening. Return in half a day. You need not earn our gratitude all over again.",
  "The roadside stall charged less than I expected. I bought enough to share, before good sense could intervene.",
  "At the inn I rested my feet and felt my strength return. Someone had kept a chair by the hearth.",
  "The guildhall offers a bounty for clearing the waiting pack. Make certain you come back to collect it. That is an order.",
  "We welcome lasting treasures at the curio hall. Bring what survived. We will make room.",
  "Wild stone along the quiet residential streets. Enough to begin again, if my hands remember how.",
  "Found the wagon by the trade road. Reached it without going near the traffic. No bargain is worth a cartwheel across your ribs.",
  "The burned road clings to my boots. Each step is heavy. I remember when the Warmonger's passing was only a rumour.",
  "Fuel yard. Sticky tar. Slow going.",
  "The waystone gave me a page of old lore. No names scratched out, no helpful corrections. I copied it exactly.",
  "Another day, another creature between the gateposts. I am beginning to doubt the wisdom of gates without doors.",
  "A giant goblin guards the treasure near the coffee shop. I have marked the shop as temporarily inconvenient.",
  "Restore the lantern row. Close-set lights hold the dark back better than a lone lamp. Leave a little brightness for whoever follows.",
  "I stayed beside the ruined path until its broken stretches came whole. For once, staying was enough.",
  "Parallel roads count as one stretch toward a road reward. Two names on a map do not make two journeys.",
  "The path was repaired already. Walking it again rekindled the dim lamps and brought another road reward nearer. Even familiar footsteps matter.",
  "Take the path beside the water. It brings the next road reward closer. I would take it for the water alone.",
  "I rested within the viewpoint's light. For a little while, the distance held nothing I needed to mend.",
  "For long grass, try the open fields beyond the deep forest. I used to send you there while I made your birthday cake.",
  "The pine near the beginning of the journey yields kindly to an axe. Start there. You need not prove yourself against the hardest wood.",
  "Leave a young tree to grow. We shall need its full load of timber, and it has not finished making it.",
  "Listen before entering the ruined walls. A garrison may be waiting. Silence is cheaper than a funeral.",
  "In the harsher world, find it first. Then learn to make it.",
  "Retreat far enough from a ruin and its guards abandon the chase. A living soldier can return. Strike true, when you can.",
  "I offered the animal its favourite food. It stayed there, waiting for me. Such a small beginning for a friendship.",
  "Fed the chicken. Found an egg beneath her this morning. She regards the whole affair as her own achievement.",
  "A gentle stroke, a little more milk. The tame cow has better manners than half my former colleagues.",
  "Stroke the tame cat and it will follow for a while. I try not to take its eventual departure personally.",
  "My tame dog chased the deer away from the crops. I have promoted him. He ate the appointment letter.",
  "Crabs on the sand beside the water. You asked where I found them. I thought you were asking why I brought them home.",
  "If the animal flees beyond reach, the hunt is over. Let it go. Hunger is no excuse for chasing shadows all day.",
  "Pack a net for the hunt. A weapon does not make the catching quicker, whatever Brann claims about his sword.",
  "A shimmering animal flees remarkably fast. My estimate of its speed remains incomplete. So does my lunch.",
  ITEM_GUIDE_TIPS.slime,
  "Choose one weapon for the next foe. A crowded pack does not fight on your behalf.",
  "Return to the training hall. Take another lesson. Grow stronger. I want to see you grow old, too.",
  "Armour softens the blow. It does not make you unbreakable. I would like to retire without explaining this again.",
  "My arrow lodged in the first obstacle in its path. Unfortunately, the obstacle was not the goblin.",
  "In the deep dark, a staff reaches only a little beyond the light. Do not mistake that little for safety.",
  "A coin where the hostile creature fell. Pick it up when the fighting is done. The living still need feeding.",
  "Raven passed overhead. Purse lighter afterwards. No witnesses willing to testify.",
  "A tower in the castle I reclaimed fired in my defence. I had forgotten what it felt like to be guarded.",
  "Below the stairs, metal waits in the stone.",
  ITEM_GUIDE_TIPS.torch,
  ITEM_GUIDE_TIPS.rope,
  "We broke through the cave wall. The passage stayed open. I wrote our names beside it, before anyone could claim we had never been here.",
  "Finer ore asks more of the pickaxe. Keep your grip steady.",
  "Deep in the richer stone, precious gems. I stopped the apprentice’s pick and eased the last loose rock away by hand.",
  "Strike a vein and look around: the same metal runs through the neighbouring rock. Stone remembers its beginnings.",
  "Deeper chests, finer treasures. Know when you have enough.",
  "Supplies in the cave chest. I had expected riches. By the time I reached daylight, I knew I had found them.",
  "Gems in the deep buried treasure. We laid them on a cloth and counted them by lamplight before beginning the climb.",
  "Goblin archers in the depths. Mind the arrows before the treasure. There will always be more treasure.",
  "The red goblin kept its distance and laid snares between us. A coward can still be a dangerous enemy.",
  "A giant below ground takes a long fight to fell. Settle your breathing before you begin.",
  "Beneath the fallen cave creature, a hidden hoard. I wonder whether it had been guarding it or merely sleeping badly.",
  "The shining monster hit harder than I expected. Pretty things have nearly killed me before. Apparently I needed reminding.",
  "Bring wood to the quartermaster. That opens the fort. If only all gates asked for something we could replace.",
  "Finish the castle's task and its gates open. I remember when a familiar face was enough.",
  "Next castle, different job. Ask before unpacking.",
  "Each finished castle job leaves harder work ahead. They call it promotion. Take the rest you need before accepting.",
  "The wizard says power hums in my unspent memories. I had hoped he might ask what I remembered.",
  "Choose the wizard's calling with care. It stays with you for good. I asked for time; he asked what there was to think about.",
  "The wizard calls it Keen Eye. Hidden glints seem easier to notice now. He spoke so warmly of what I might become.",
  "A magical flower in the furnace helped turn a lesser bar into finer metal. I kept one petal outside the heat. For the colour.",
  "Seek magical flowers out in the world. No shop sells their seeds. Some things still refuse to sit on a shelf.",
  "Might sapphire soothe a slime? Brann says to kill it. But there must be something beneath that trembling besides malice.",
  "In the harsher world, even a small bite leaves me trembling. I used to laugh at the old warnings.",
  "When the harsher world takes your last strength, seek your own trailer. Shelter first. Pride can spend the night outside.",
  ITEM_GUIDE_TIPS.crow_feather,
  // Appended (Sep 2026, the gull's food theft): a new page goes LAST so every
  // saved bookmark (save.tipsRead) still opens on the page it was left at.
  "A gull took the best of my lunch from the top of the bag. It did not so much as land.",
  // Appended (Sep 2026): the road's bargain — each stretch it asks for runs
  // longer than the last, and pays finer (trail.js goalFor / rollBonusFor).
  "Each stretch of road they ask me to mend runs longer than the last. What waits at the end of it is finer, too. I have stopped asking who set the terms.",
  // Appended (Oct 2026): the spear, made at Home from a stone and a branch
  // (items.js HOME_RECIPES) — every craftable has its page in the Book.
  ITEM_GUIDE_TIPS.throwing_spear,
  ITEM_GUIDE_TIPS.taming_potion,
  ITEM_GUIDE_TIPS.fireball_scroll,
  ITEM_GUIDE_TIPS.fear_scroll,
  ITEM_GUIDE_TIPS.treasure_map,
  "Joined the book club at the school booth. The scholars count every book I read and take a tome down from the shelf as the pile grows. Bought ones count too, at a climbing price.",
  // Append new guides after all published pages to preserve saved bookmarks.
  ITEM_GUIDE_TIPS.thunder_scroll,
  ITEM_GUIDE_TIPS.raven_scroll,
  ITEM_GUIDE_TIPS.bones_scroll,
  ITEM_GUIDE_TIPS.wraith_scroll,
];

// Volume voices are editorial guidance as well as the attribution shown in the reader.
const BOOK_VOLUMES = {
  "key": {
    "title": "The Key We Kept",
    "author": "Mara Vale",
    "voice": "Plain, hopeful family notes; small possessions carry loss."
  },
  "builder": {
    "title": "Letters to My Son",
    "author": "Ada Fen",
    "voice": "Grieving builder; practical tenderness, unfinished domestic thoughts."
  },
  "ash": {
    "title": "After the Roofs Fell",
    "author": "Tomas Reed",
    "voice": "Restrained survivor testimony; destruction remembered through absences."
  },
  "road": {
    "title": "The Unfinished Journey",
    "author": "Iven Marr",
    "voice": "Wary, lonely traveller; brief observations, no neat explanations."
  },
  "names": {
    "title": "The Missing Names",
    "author": "Sera Venn",
    "voice": "Archivist troubled by gaps and corrections; uncertain, never prophetic."
  },
  "brann": {
    "title": "Sergeant Brann’s Field Manual",
    "author": "Sergeant Brann",
    "voice": "Protective veteran; clipped orders, occasional dry rebuke, Strike true sparingly."
  },
  "scholar": {
    "title": "Notes on Uncooperative Fauna",
    "author": "Dr Pell",
    "voice": "Distracted field scholar; formal observations undermined by small mishaps."
  },
  "warden": {
    "title": "Road Warden’s Notices",
    "author": "Office of the Road Warden",
    "voice": "Official, direct safety notices; no jokes or ornamental framing."
  },
  "soldier": {
    "title": "A Small Act of Treason",
    "author": "Unsigned",
    "voice": "Guilty former soldier; concrete acts, no plea for forgiveness."
  },
  "garden": {
    "title": "What We Can Grow",
    "author": "Ada Fen",
    "voice": "Patient gardening letters; food and seasons as modest reasons to continue."
  },
  "ledger": {
    "title": "An Honest Account, Mostly",
    "author": "Nell Quill",
    "voice": "Trader’s terse ledger; selective honesty and occasional dry humour."
  },
  "coast": {
    "title": "Low Water",
    "author": "Nell Quill",
    "voice": "Coastal notebook; rueful humour and practical curiosity."
  },
  "fish": {
    "title": "Letters from the Bank",
    "author": "Orin Pike",
    "voice": "Fond sibling rivalry; fishing disappointments, occasional comic understatement."
  },
  "civic": {
    "title": "A Town Worth Returning To",
    "author": "Mara Vale",
    "voice": "Civic recollections; personal dignity and ordinary hospitality."
  },
  "miner": {
    "title": "Understone Apprenticeship",
    "author": "Master Hedd",
    "voice": "Blunt mining teacher; patient craft beneath a gruff manner."
  },
  "lamps": {
    "title": "A Light for the Next Walker",
    "author": "Warden Edda",
    "voice": "Earnest road keeper; communal work and quiet beauty."
  },
  "forge": {
    "title": "At the Mended Forge",
    "author": "Master Hedd",
    "voice": "Craft notebook; work observed precisely, rare flashes of tenderness."
  },
  "wizard": {
    "title": "Lessons at the Tower",
    "author": "Sera Venn",
    "voice": "Apprentice’s private notes; admiration unsettled by unanswered questions."
  }
};

const PLAY_TIP_VOLUMES = [
  "key",
  "builder",
  "ash",
  "builder",
  "road",
  "builder",
  "names",
  "ledger",
  "builder",
  "road",
  "brann",
  "scholar",
  "builder",
  "warden",
  "soldier",
  "warden",
  "warden",
  "warden",
  "warden",
  "road",
  "garden",
  "garden",
  "scholar",
  "garden",
  "builder",
  "builder",
  "garden",
  "garden",
  "scholar",
  "brann",
  "brann",
  "brann",
  "key",
  "key",
  "builder",
  "ledger",
  "coast",
  "coast",
  "ledger",
  "ledger",
  "ledger",
  "ledger",
  "ledger",
  "ledger",
  "road",
  "garden",
  "names",
  "ledger",
  "road",
  "road",
  "road",
  "fish",
  "fish",
  "fish",
  "fish",
  "garden",
  "brann",
  "civic",
  "civic",
  "civic",
  "civic",
  "ledger",
  "ledger",
  "ledger",
  "civic",
  "ledger",
  "civic",
  "brann",
  "civic",
  "builder",
  "ledger",
  "ash",
  "brann",
  "names",
  "ledger",
  "ledger",
  "lamps",
  "lamps",
  "lamps",
  "lamps",
  "lamps",
  "road",
  "garden",
  "builder",
  "builder",
  "brann",
  "miner",
  "brann",
  "scholar",
  "scholar",
  "scholar",
  "scholar",
  "scholar",
  "scholar",
  "brann",
  "scholar",
  "scholar",
  "scholar",
  "brann",
  "brann",
  "brann",
  "scholar",
  "brann",
  "brann",
  "ledger",
  "road",
  "miner",
  "miner",
  "miner",
  "miner",
  "miner",
  "miner",
  "miner",
  "miner",
  "miner",
  "miner",
  "brann",
  "brann",
  "brann",
  "scholar",
  "brann",
  "brann",
  "brann",
  "ledger",
  "brann",
  "wizard",
  "wizard",
  "wizard",
  "forge",
  "garden",
  "scholar",
  "ash",
  "road",
  "road",
  "ledger",
  "road",
  "brann",
  "garden",
  "road",
  "road",
  "road",
  "ledger",
  "wizard",
  "wizard",
  "wizard",
  "wizard",
];

// Narrator observations sit outside the quoted excerpt.
const PLAY_TIP_ASIDES = {
  "0": "a few passages stand out",
  "2": "Rain has blurred the final line.",
  "4": "A thumbprint darkens the corner.",
  "6": "Someone had scraped a name from the page.",
  "10": "The spine is repaired with bootlace.",
  "12": "A pressed flower falls from the pages.",
  "14": "A military crest has been cut away.",
  "20": "A garden plan fills the facing page.",
  "23": "A seed husk is caught in the fold.",
  "25": "The binding smells faintly of smoke.",
  "30": "This line is underlined.",
  "32": "The bottom of the page is smoke-stained.",
  "34": "The paper is worn thin at the fold.",
  "36": "Sand catches in the stitching.",
  "39": "Two different inks mark the entries.",
  "40": "The entry has been checked twice.",
  "43": "The corner has been folded into a triangle.",
  "46": "The ink trails off.",
  "47": "A price has been added in pencil.",
  "51": "The page curls where it once got wet.",
  "53": "A fish scale clings to the paper.",
  "55": "A brown leaf marks this passage.",
  "58": "A list of names fills the opposite page.",
  "60": "Someone has ticked off the names in the margin.",
  "63": "Several sums have been crossed out.",
  "66": "A ring from a cup crosses the last line.",
  "68": "The library stamp is still legible.",
  "73": "The letters were copied in a careful hand.",
  "76": "A small lantern is drawn beside the heading.",
  "81": "There is a sketch of distant hills.",
  "83": "The cover has been patched with cloth.",
  "86": "A careful drawing fills the opposite page.",
  "89": "A small beak has punctured the corner.",
  "92": "The corner appears to have been chewed.",
  "97": "Blue dust stains the binding.",
  "101": "A neat hole pierces several pages.",
  "106": "Grit falls from the spine.",
  "109": "Three names are underlined.",
  "111": "Mineral dust has settled into the paper.",
  "114": "A strip of cloth marks the page.",
  "125": "The margins are crowded with unanswered questions.",
  "127": "A circle has been pressed into the paper.",
  "128": "A faded petal is tucked against the spine.",
  "133": "A black feather marks the passage."
};

// The pages a save has read so far, in reading order — the course walks
// PLAY_TIPS from page one (app.js _bookRead keeps the bookmark in
// save.tipsRead, unwrapped), so the pages read are the first min(tipsRead,
// PLAY_TIPS.length) of them. The Books chip (app.js _buildBookChip) counts
// them and its list offers them to read again.
function bookPagesRead(save) {
  const read = Math.max(0, Math.floor(Number(save && save.tipsRead) || 0));
  const n = Math.min(read, PLAY_TIPS.length);
  return Array.from({ length: n }, (_, i) => i);
}
// One line to name a page in a list: its volume's title and author.
function bookPageLabel(page) {
  const volume = BOOK_VOLUMES[PLAY_TIP_VOLUMES[page]];
  return `${volume.title} · ${volume.author}`;
}
function bookPageHTML(page) {
  const volume = BOOK_VOLUMES[PLAY_TIP_VOLUMES[page]];
  const aside = PLAY_TIP_ASIDES[page];
  const escape = (text) => text.replace(/[&<>"']/g, (ch) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]));
  return `<div class="book-volume"><strong>${escape(volume.title)}</strong> · ${escape(volume.author)}</div><br>`
    + (aside ? `<em>${escape(aside)}</em><br><br>` : '')
    + `<div class="story-copy">“${escape(PLAY_TIPS[page])}”</div>`;
}
