// Story pages keep their saved-bookmark order. Each carries one useful discovery.
// Real-world safety pages speak directly so their guidance stays clear.
const PLAY_TIPS = [
  "Leave weary hands to rest awhile; strength returns even while you are away.",
  "In the harsher world, even a small bite leaves you trembling.",
  "When the harsher world takes your last strength, seek the shelter of your own trailer.",
  ITEM_GUIDE_TIPS.crow_feather,
  "Only beneath your own roof can you sink into the deep rest of home.",
  "A campfire warms tired hands until they are ready to work again.",
  "Finish the work before you settle into a proper rest.",
  "Bring the day's haul home, where it can become a little money.",
  "Even bare hands can do the work, if you have patience.",
  "Below ground, your light draws closer with every descent.",
  "Your blows land strongest where your own footsteps fall.",
  "Watch the colour above a foe fade from green toward red as its strength fails.",
  "The closing circle tells how near your work is to its end.",
  "Step clear of a sprung snare; its jaws keep hurting while you linger.",
  ITEM_GUIDE_TIPS.trap_kit,
  "Stay on the pavement beside a busy road to escape a chase. Never step into the road to play.",
  "Reach things across a street with the game's stick. Never enter the road to collect them.",
  "The game pauses while you travel faster than a run. Play only when you are safely on foot.",
  "On hot days, carry water, stay in the shade and rest often.",
  "After nightfall, listen for ghosts stirring in the dark.",
  "Clear the soil before asking the hoe to turn it.",
  "A watered crop keeps growing while you are away.",
  "Bring an Antidote below; a purple slime's sickness can outlast the fight.",
  "Look among the harvest for a seed to begin again.",
  "Stone and care can give a ruined house its roof again.",
  "Your first restored house will ring with the sound of your own smithy.",
  "Keep crops close to Home, beyond the reach of hungry raiders.",
  ITEM_GUIDE_TIPS.scarecrow,
  "Stay beside a wild slime and you will feel your strength draining.",
  "Give the biting plants a wide berth; their roots keep them in place.",
  "A wounded slime stops wandering and rushes at whoever struck it.",
  "To land a blow, you must come close enough to feel the creature's breath.",
  "At Home's edge, pursuing creatures turn away.",
  "Taste something new; a little of its strength will stay with you for good.",
  "An imperfect tool can sometimes finish a stubborn job, with patience.",
  "Every car park keeps a treasure buried beneath its X.",
  "Shore sand holds buried treasure thickly beneath your feet.",
  "The farmer returned to the waterline another day and found fresh gifts from the sea.",
  "The finer the gem above a chest, the finer the promise within.",
  "A lone chest shone more brightly than crates crowded together.",
  "Give an emptied plain crate time; it will hold something again.",
  "Most barrels answer with a hollow sound and nothing inside.",
  "The pot of gold had another handful of coins to offer when the farmer returned a later day.",
  "At the courier's post, the farmer borrowed a fleeting swiftness for their wandering double.",
  "A glow lingered over the unopened gift, inviting the farmer closer.",
  "A stone lifted from the ground sometimes reveals a gemfruit.",
  "An unfamiliar find stirred a forgotten memory in the farmer.",
  "The shimmering flower fetched a finer price than its plain neighbour.",
  "Visit the park shrine another day for another gift.",
  "Touch a headstone with care; it may wake a ghost.",
  "At the heart of the grove, the farmer found a chest richer than those around it.",
  "A fine fish may slip a poor rod's hook, waiting for you to return better prepared.",
  "A golden glint on the water betrayed a shiny fish below.",
  "Sometimes the heavy fishing line brings up an indignant slime.",
  "Even an empty fishing spot can yield a little treasure.",
  "Turn the soil and something long buried may come to light.",
  "Look for the smith behind a door whose number ends in nine.",
  "Restore more shops and you will find new wares on their shelves.",
  "A household pays generously for the produce on its wishlist.",
  "A household keeps its old wishlist, patiently awaiting the same bundle.",
  "After many deliveries, newly restored households began asking for finer crops.",
  "Give the shopkeeper time between deals.",
  ITEM_GUIDE_TIPS.flowers,
  "The fort's reels rattle to a stop; matching pictures bring a prize.",
  "A reclaimed castle has one favour to offer each day.",
  "A roadside stall offers a gentler price than usual.",
  "At the inn, you can rest tired feet and recover strength.",
  "The guildhall promised a bounty for clearing the waiting pack.",
  "The curio hall welcomes lasting treasures into its collection.",
  "Some quiet residential streets are lined with wild stone.",
  "An old wagon waited by the trade road, far from any reason to enter traffic.",
  "A burned road clings to your boots and makes each step heavy.",
  "Sticky tar near a fuel yard slows your steps.",
  "A weathered waystone will share a page of old lore.",
  "Another day dawned, and a creature emerged between the gateposts.",
  "A giant goblin guarded the treasure near the coffee shop.",
  "Restore the lantern row and its close-set lights will push back the dark.",
  "Linger beside a ruined path and its broken stretches will come whole again.",
  "Where roads ran beside each other, their restoration counted as a single stretch toward a reward.",
  "The path was already repaired, but walking it again rekindled its dim lamps. Even familiar footsteps brought the farmer closer to another road reward.",
  "A path beside the water brings your next road reward closer.",
  "Within the viewpoint's light, the farmer rested and watched the distance.",
  "Look for long grass in open fields beyond the deep forest.",
  "The pine near your journey's beginning yields kindly to the axe.",
  "Let a young tree grow before asking it for a full load of timber.",
  "Listen beyond the ruined walls; a garrison may be waiting.",
  "In the harsher world, first find a thing before learning to make it.",
  "Get far enough from a ruin and its guards will give up the chase.",
  "Share an animal's favourite food and a friend will wait there in the world.",
  "A well-fed chicken left an egg for the farmer.",
  "A gentle stroke may persuade a tame cow to give a little more milk.",
  "Stroke a tame cat and it will follow for a while.",
  "The tame dog chased hungry deer away from the farmer's crops.",
  "Look for crabs on sand beside the water.",
  "Let the animal flee beyond reach and the hunt is over.",
  "Bring a net for the hunt; a weapon will not make it quicker.",
  "A shimmering animal flees with startling speed.",
  ITEM_GUIDE_TIPS.slime,
  "Choose one weapon to answer your next foe.",
  "Repeated lessons at a training hall make you stronger.",
  "Armour softens a blow, though you will still feel it land.",
  "The arrow buried itself in the first obstacle along its flight.",
  "In the deep dark, your staff reaches only a little beyond the light.",
  "Look where a hostile creature fell; a coin waits to be gathered.",
  "The gull swooped past, leaving the farmer's purse lighter.",
  "From the reclaimed castle, a tower loosed an arrow in the farmer's defence.",
  "Below the stairs, metal waits in the stone.",
  ITEM_GUIDE_TIPS.torch,
  ITEM_GUIDE_TIPS.rope,
  "Break through a cave wall and the passage stays open.",
  "Finer ore asks more effort of your pickaxe.",
  "Deep within richer stone, the farmer found precious gems.",
  "Strike a vein and the same metal runs through the surrounding rock.",
  "The deeper you go, the finer the treasures in the chests.",
  "The cave chest held supplies for the farmer's journey below.",
  "Deep buried treasures sometimes held gems among their gifts.",
  "Watch for goblin archers in the depths.",
  "The red goblin hung back, laying snares between itself and the farmer.",
  "A giant in the depths will take a long fight to fell.",
  "Beneath a cave creature, the farmer sometimes found a hidden hoard.",
  "The shining monster struck with frightening force.",
  "Bring wood to the quartermaster to open the fort.",
  "Finish the castle's task and its gates will open to you.",
  "The next castle offered a different job from the last.",
  "With each finished castle job, the work ahead grows more demanding.",
  "The wizard hears power humming in your unspent memories.",
  "Consider the wizard's calling carefully; it stays with you for good.",
  "The wizard's Keen Eye can place a Ring on your hand.",
  "In the furnace, a magical flower helped turn a lesser bar into finer metal.",
  "Seek magical flowers in the world; shops cannot supply their seeds.",
  "The old texts whispered of sapphire, and a slime that might be gentler than it seemed.",
];
